{
  "hash": "001c6cb5a9bc346f490ed4cb0bf7bbb7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"LCA Model Design\"\nauthor: \"Xiaohan Zhang\"\ndate: \"2025-3-26\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n\n\n## 1. Introduction\n- Brief overview of the property price analysis using Latent Class Analysis\n- Explanation of why LCA is appropriate for market segmentation\n- Research questions being addressed\n\n## 2. R Packages Assessment and Selection\n- `poLCA`: Core package for latent class analysis implementation\n- `tidyverse`: For data preparation and categorical variable creation\n- `ggplot2`: For visualization of class probabilities and model comparison\n- `mclust`: For model evaluation and entropy calculation\n- Justification for each package selection\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load packages\nlibrary(readxl)      # For reading Excel files\nlibrary(tidyverse)   # For data manipulation and visualization\nlibrary(poLCA)       # For latent class analysis\nlibrary(mclust)      # For model evaluation\nlibrary(DT)          # For interactive data tables\nlibrary(plotly)      # For interactive plots\n```\n:::\n\n\n\n\n\n## 3. Data Preparation and Testing\n\n### Dataset Overview\nThe analysis is based on a comprehensive property price dataset containing 52,644 observations across 28 variables. The dataset includes crucial property characteristics and location-based features. Key variables in the dataset include property prices (the target variable), physical property attributes (size, floor level, highest floor in building, number of units), location-specific features (distances to green spaces, water, subway stations, CBD), environmental quality indicators (Green Index), and demographic information (population density, education levels, age distributions). The data spans properties with sizes ranging from 12.49 to 269.68 square meters, located on floors ranging from -1 to 77, with varying accessibility to amenities.\n\nA thorough examination of the dataset structure revealed complete data with no missing values across all variables. This completeness provided an excellent foundation for reliable latent class analysis without the need for imputation or handling of missing data. The data also displays considerable variation across all key variables, suggesting the potential for meaningful market segmentation.\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nProperty_data <- read_excel(\"data/Property_Price_and_Green_Index.xlsx\")\n\nglimpse(Property_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 52,644\nColumns: 28\n$ `Property Prices`  <dbl> 9.798127, 9.852194, 9.740969, 9.798127, 9.692767, 9…\n$ Longitude          <dbl> 129.1081, 129.1081, 129.1081, 129.1081, 129.1081, 1…\n$ Latitude           <dbl> 35.21502, 35.21502, 35.21502, 35.21502, 35.21502, 3…\n$ Size               <dbl> 45.0700, 38.1000, 45.0700, 38.1000, 38.1000, 45.070…\n$ Floor              <dbl> 8, 13, 6, 13, 7, 9, 6, 6, 11, 7, 9, 9, 10, 11, 2, 4…\n$ `Highest floor`    <dbl> 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 11, 11,…\n$ Units              <dbl> 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 8, 8, 8…\n$ Parking            <dbl> 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.6…\n$ Heating            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Year               <dbl> 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 201…\n$ `Dist. Green`      <dbl> 4.668050, 4.668050, 4.668050, 4.668050, 4.668050, 4…\n$ `Dist. Water`      <dbl> 7.092015, 7.092015, 7.092015, 7.092015, 7.092015, 7…\n$ `Green Index`      <dbl> 10.867812, 10.867812, 10.867812, 10.867812, 10.8678…\n$ `Dist. Subway`     <dbl> 5.655021, 5.655021, 5.655021, 5.655021, 5.655021, 5…\n$ `Bus Stop`         <dbl> 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 13, 13, 13, …\n$ `Dist. CBD`        <dbl> 19909.90, 19909.90, 19909.90, 19909.90, 19909.90, 1…\n$ `Top Univ.`        <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `High School`      <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …\n$ `Sex Ratio`        <dbl> 97.83177, 97.83177, 97.83177, 97.83177, 97.83177, 9…\n$ Population         <dbl> 31022, 31022, 31022, 31022, 31022, 31022, 31022, 33…\n$ `Pop. Density`     <dbl> 1637.045, 1637.045, 1637.045, 1637.045, 1637.045, 1…\n$ `Higher Degree`    <dbl> 46.39234, 46.39234, 46.39234, 46.39234, 46.39234, 4…\n$ `Young Population` <dbl> 26.28457, 26.28457, 26.28457, 26.28457, 26.28457, 2…\n$ `Median Age`       <dbl> 55.4, 55.4, 55.4, 55.4, 55.4, 55.4, 55.4, 55.4, 55.…\n$ `Old Population`   <dbl> 5.712075, 5.712075, 5.712075, 5.712075, 5.712075, 5…\n$ Spring             <dbl> 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, …\n$ Fall               <dbl> 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, …\n$ Winter             <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, …\n```\n\n\n:::\n:::\n\n\n\n\n### Variable Discretization Process\nFor effective latent class analysis, continuous variables were transformed into categorical format. This discretization process is essential as LCA requires categorical indicators. A quantile-based approach was primarily employed to ensure balanced distribution of observations across categories while preserving meaningful differentiation between property types.\n\nFor most variables, tertile cutpoints (33rd and 66th percentiles) were used to create three distinct categories representing low (1), medium (2), and high (3) values. This approach was applied to Size, Green Index, Subway Distance, Population Density, and Median Age variables. The rationale for using tertiles rather than quartiles or quintiles was to maintain sufficient observation counts in each category while still capturing meaningful differentiation.\n\nFor Floor categorization, however, a different approach was taken. Instead of percentile-based cutpoints, more intuitive fixed cutpoints were employed: low floors (≤5), medium floors (≤10), and high floors (>10). This choice reflects typical building classifications and aligns with common property market segmentation practices where floor level represents a distinct feature of vertical positioning, often associated with views, noise levels, and accessibility considerations.\n\n### Frequency Distribution Verification\nFollowing the discretization process, thorough verification of frequency distributions was conducted to ensure the effectiveness of the categorization. The frequency tables for each categorical variable confirmed generally balanced categories with sufficient observations in each group to support stable LCA estimation.\n\nSize categories showed excellent balance with approximately 33% of observations in each category (17,374 in category 1, 17,609 in category 2, and 17,661 in category 3). Similar balanced distributions were observed for Green Index categories, Subway Distance categories, and Population Density categories, all showing approximately equal distribution across the three levels.\n\nFloor categories showed a somewhat different distribution pattern, with a higher concentration of properties in category 3 (floors above 10) comprising 26,406 observations, while categories 1 and 2 contained 13,004 and 13,234 observations respectively. This distribution reflects the actual property landscape in the dataset, with a predominance of properties located on higher floors.\n\nMedian Age categories also showed a relatively balanced distribution (17,670 in category 1, 18,504 in category 2, and 16,470 in category 3), with a slightly higher number of properties in areas with middle-aged populations.\n\nThese distribution verifications confirmed that the discretization process produced meaningful categories with sufficient observations for robust LCA modeling, enabling the identification of distinct property market segments.\n\n\nStep 2: Data Preparation and Checking\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data (assuming you've already loaded it)\n# Property_data <- read_excel(\"data/Property_Price_and_Green_Index.xlsx\")\n\n# 1. Initial data checking\nstr(Property_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [52,644 × 28] (S3: tbl_df/tbl/data.frame)\n $ Property Prices : num [1:52644] 9.8 9.85 9.74 9.8 9.69 ...\n $ Longitude       : num [1:52644] 129 129 129 129 129 ...\n $ Latitude        : num [1:52644] 35.2 35.2 35.2 35.2 35.2 ...\n $ Size            : num [1:52644] 45.1 38.1 45.1 38.1 38.1 ...\n $ Floor           : num [1:52644] 8 13 6 13 7 9 6 6 11 7 ...\n $ Highest floor   : num [1:52644] 13 13 13 13 13 13 13 13 13 13 ...\n $ Units           : num [1:52644] 84 84 84 84 84 84 84 84 84 84 ...\n $ Parking         : num [1:52644] 0.67 0.67 0.67 0.67 0.67 0.67 0.67 0.67 0.67 0.67 ...\n $ Heating         : num [1:52644] 0 0 0 0 0 0 0 0 0 0 ...\n $ Year            : num [1:52644] 2017 2017 2017 2017 2017 ...\n $ Dist. Green     : num [1:52644] 4.67 4.67 4.67 4.67 4.67 ...\n $ Dist. Water     : num [1:52644] 7.09 7.09 7.09 7.09 7.09 ...\n $ Green Index     : num [1:52644] 10.9 10.9 10.9 10.9 10.9 ...\n $ Dist. Subway    : num [1:52644] 5.66 5.66 5.66 5.66 5.66 ...\n $ Bus Stop        : num [1:52644] 5 5 5 5 5 5 6 6 6 6 ...\n $ Dist. CBD       : num [1:52644] 19910 19910 19910 19910 19910 ...\n $ Top Univ.       : num [1:52644] 0 0 0 0 0 0 0 0 0 0 ...\n $ High School     : num [1:52644] 2 2 2 2 2 2 2 2 2 2 ...\n $ Sex Ratio       : num [1:52644] 97.8 97.8 97.8 97.8 97.8 ...\n $ Population      : num [1:52644] 31022 31022 31022 31022 31022 ...\n $ Pop. Density    : num [1:52644] 1637 1637 1637 1637 1637 ...\n $ Higher Degree   : num [1:52644] 46.4 46.4 46.4 46.4 46.4 ...\n $ Young Population: num [1:52644] 26.3 26.3 26.3 26.3 26.3 ...\n $ Median Age      : num [1:52644] 55.4 55.4 55.4 55.4 55.4 55.4 55.4 55.4 55.4 55.4 ...\n $ Old Population  : num [1:52644] 5.71 5.71 5.71 5.71 5.71 ...\n $ Spring          : num [1:52644] 0 1 1 0 0 0 0 0 0 0 ...\n $ Fall            : num [1:52644] 0 0 0 0 0 0 1 1 1 0 ...\n $ Winter          : num [1:52644] 1 0 0 0 0 0 0 0 0 1 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(Property_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Property Prices    Longitude        Latitude          Size       \n Min.   : 6.908   Min.   :128.8   Min.   :35.05   Min.   : 12.49  \n 1st Qu.: 9.831   1st Qu.:129.0   1st Qu.:35.14   1st Qu.: 59.82  \n Median :10.174   Median :129.1   Median :35.17   Median : 79.36  \n Mean   :10.187   Mean   :129.1   Mean   :35.17   Mean   : 77.82  \n 3rd Qu.:10.558   3rd Qu.:129.1   3rd Qu.:35.20   3rd Qu.: 84.98  \n Max.   :12.934   Max.   :129.3   Max.   :35.37   Max.   :269.68  \n     Floor       Highest floor       Units           Parking      \n Min.   :-1.00   Min.   : 2.00   Min.   :   4.0   Min.   : 0.000  \n 1st Qu.: 6.00   1st Qu.:15.00   1st Qu.: 301.0   1st Qu.: 0.870  \n Median :11.00   Median :24.00   Median : 690.0   Median : 1.040  \n Mean   :11.82   Mean   :23.25   Mean   : 937.1   Mean   : 1.101  \n 3rd Qu.:16.00   3rd Qu.:26.00   3rd Qu.:1280.0   3rd Qu.: 1.250  \n Max.   :77.00   Max.   :84.00   Max.   :5239.0   Max.   :77.000  \n    Heating             Year       Dist. Green       Dist. Water     \n Min.   :0.00000   Min.   :1969   Min.   : 0.8081   Min.   :-0.1703  \n 1st Qu.:0.00000   1st Qu.:1996   1st Qu.: 5.4695   1st Qu.: 5.5656  \n Median :0.00000   Median :2004   Median : 6.4194   Median : 6.4094  \n Mean   :0.09331   Mean   :2003   Mean   : 7.2765   Mean   : 6.2683  \n 3rd Qu.:0.00000   3rd Qu.:2013   3rd Qu.: 9.7661   3rd Qu.: 7.1239  \n Max.   :1.00000   Max.   :2019   Max.   :10.7145   Max.   : 8.6013  \n  Green Index      Dist. Subway      Bus Stop      Dist. CBD       \n Min.   : 4.163   Min.   :3.366   Min.   : 0.0   Min.   :   243.9  \n 1st Qu.: 9.117   1st Qu.:6.212   1st Qu.:10.0   1st Qu.:  8280.6  \n Median :10.715   Median :6.771   Median :16.0   Median :398855.8  \n Mean   :10.733   Mean   :6.892   Mean   :18.1   Mean   :237377.3  \n 3rd Qu.:12.128   3rd Qu.:7.408   3rd Qu.:25.0   3rd Qu.:398855.9  \n Max.   :18.927   Max.   :9.978   Max.   :63.0   Max.   :398856.1  \n   Top Univ.      High School      Sex Ratio        Population   \n Min.   : 0.00   Min.   : 0.00   Min.   : 81.02   Min.   : 1208  \n 1st Qu.: 6.00   1st Qu.: 8.00   1st Qu.: 92.94   1st Qu.:15639  \n Median :13.00   Median :14.00   Median : 95.59   Median :24412  \n Mean   :11.18   Mean   :14.27   Mean   : 95.75   Mean   :25888  \n 3rd Qu.:17.00   3rd Qu.:21.00   3rd Qu.: 97.80   3rd Qu.:31399  \n Max.   :27.00   Max.   :30.00   Max.   :124.51   Max.   :83116  \n  Pop. Density    Higher Degree   Young Population   Median Age  \n Min.   :     1   Min.   :10.36   Min.   : 3.151   Min.   :32.7  \n 1st Qu.:  6905   1st Qu.:24.25   1st Qu.: 9.500   1st Qu.:40.8  \n Median : 11126   Median :28.93   Median :11.332   Median :42.8  \n Mean   : 13221   Mean   :30.30   Mean   :12.120   Mean   :42.6  \n 3rd Qu.: 17618   3rd Qu.:36.03   3rd Qu.:13.904   3rd Qu.:44.4  \n Max.   :118182   Max.   :61.29   Max.   :26.285   Max.   :55.4  \n Old Population       Spring            Fall            Winter      \n Min.   : 5.712   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:13.895   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :16.116   Median :0.0000   Median :0.0000   Median :0.0000  \n Mean   :16.325   Mean   :0.2152   Mean   :0.3432   Mean   :0.2433  \n 3rd Qu.:18.724   3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:0.0000  \n Max.   :33.292   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Check for missing values\nmissing_values <- colSums(is.na(Property_data))\nprint(missing_values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Property Prices        Longitude         Latitude             Size \n               0                0                0                0 \n           Floor    Highest floor            Units          Parking \n               0                0                0                0 \n         Heating             Year      Dist. Green      Dist. Water \n               0                0                0                0 \n     Green Index     Dist. Subway         Bus Stop        Dist. CBD \n               0                0                0                0 \n       Top Univ.      High School        Sex Ratio       Population \n               0                0                0                0 \n    Pop. Density    Higher Degree Young Population       Median Age \n               0                0                0                0 \n  Old Population           Spring             Fall           Winter \n               0                0                0                0 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Variable discretization (example - adjust based on actual data distribution)\n# Prepare data for LCA by selecting appropriate variables and discretizing\n\nProperty_data_lca <- Property_data %>%\n  mutate(\n    # Size categorization (based on quantiles)\n    Size_cat = case_when(\n      Size <= quantile(Size, 0.33) ~ 1,\n      Size <= quantile(Size, 0.66) ~ 2,\n      TRUE ~ 3\n    ),\n    \n    # Floor categorization\n    Floor_cat = case_when(\n      Floor <= 5 ~ 1,\n      Floor <= 10 ~ 2,\n      TRUE ~ 3\n    ),\n    \n    # Green Index categorization\n    Green_Index_cat = case_when(\n      `Green Index` <= quantile(`Green Index`, 0.33) ~ 1,\n      `Green Index` <= quantile(`Green Index`, 0.66) ~ 2,\n      TRUE ~ 3\n    ),\n    \n    # Distance to subway categorization\n    Subway_Dist_cat = case_when(\n      `Dist. Subway` <= quantile(`Dist. Subway`, 0.33) ~ 1,\n      `Dist. Subway` <= quantile(`Dist. Subway`, 0.66) ~ 2,\n      TRUE ~ 3\n    ),\n    \n    # Population density categorization\n    Pop_Density_cat = case_when(\n      `Pop. Density` <= quantile(`Pop. Density`, 0.33) ~ 1,\n      `Pop. Density` <= quantile(`Pop. Density`, 0.66) ~ 2,\n      TRUE ~ 3\n    ),\n    \n    # Median Age categorization\n    Median_Age_cat = case_when(\n      `Median Age` <= quantile(`Median Age`, 0.33) ~ 1,\n      `Median Age` <= quantile(`Median Age`, 0.66) ~ 2,\n      TRUE ~ 3\n    )\n  )\n\n# Check frequency distribution of categorical variables\nlca_vars <- c(\"Size_cat\", \"Floor_cat\", \"Green_Index_cat\", \"Subway_Dist_cat\", \n              \"Pop_Density_cat\", \"Median_Age_cat\")\n\nfor(var in lca_vars) {\n  cat(\"\\nFrequency table for\", var, \":\\n\")\n  print(table(Property_data_lca[[var]]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFrequency table for Size_cat :\n\n    1     2     3 \n17374 17609 17661 \n\nFrequency table for Floor_cat :\n\n    1     2     3 \n13004 13234 26406 \n\nFrequency table for Green_Index_cat :\n\n    1     2     3 \n17374 17404 17866 \n\nFrequency table for Subway_Dist_cat :\n\n    1     2     3 \n17384 17395 17865 \n\nFrequency table for Pop_Density_cat :\n\n    1     2     3 \n17521 17271 17852 \n\nFrequency table for Median_Age_cat :\n\n    1     2     3 \n17670 18504 16470 \n```\n\n\n:::\n:::\n\n\n\n\n\nStep 3: LCA Model Fitting and Evaluation\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create formula\nf <- cbind(Size_cat, Floor_cat, Green_Index_cat, Subway_Dist_cat, \n           Pop_Density_cat, Median_Age_cat) ~ 1\n\n# Set range of classes from 3 to 8\nmin_classes <- 3\nmax_classes <- 8\n\n# Store model results\nlca_results <- list()\nlca_stats <- data.frame(n_classes = min_classes:max_classes)\n\n# Entropy calculation function\nentropy <- function(posterior) {\n  entropy <- -rowSums(posterior * log(posterior), na.rm = TRUE)\n  max_entropy <- -log(1/ncol(posterior))\n  return(1 - mean(entropy) / max_entropy)\n}\n\nset.seed(123)  # For reproducibility\n\n# Previous BIC value for early stopping\nprev_bic <- Inf\nconsecutive_increases <- 0\nmax_consecutive_increases <- 2  # Stop after 2 consecutive BIC increases\n\nfor (i in min_classes:max_classes) {\n  cat(\"\\nFitting model with\", i, \"classes...\\n\")\n  \n  # Optimize for speed\n  lca_results[[i]] <- poLCA(f, Property_data_lca, nclass = i, \n                           maxiter = 1000, nrep = 10)\n  \n  # Store fit statistics\n  idx <- i - min_classes + 1\n  lca_stats$logLik[idx] <- lca_results[[i]]$llik\n  lca_stats$BIC[idx] <- lca_results[[i]]$bic\n  lca_stats$AIC[idx] <- lca_results[[i]]$aic\n  lca_stats$df[idx] <- lca_results[[i]]$resid.df\n  lca_stats$Entropy[idx] <- entropy(lca_results[[i]]$posterior)\n  \n  # Print summary information\n  cat(\"Log-likelihood:\", lca_results[[i]]$llik, \"\\n\")\n  cat(\"BIC:\", lca_results[[i]]$bic, \"\\n\")\n  cat(\"AIC:\", lca_results[[i]]$aic, \"\\n\")\n  \n  # Early stopping check\n  current_bic <- lca_results[[i]]$bic\n  if (current_bic > prev_bic) {\n    consecutive_increases <- consecutive_increases + 1\n    cat(\"BIC increased. Consecutive increases:\", consecutive_increases, \"\\n\")\n    \n    if (consecutive_increases >= max_consecutive_increases) {\n      cat(\"\\nEarly stopping triggered after\", consecutive_increases, \n          \"consecutive BIC increases. Optimal classes may be\", i - consecutive_increases, \"\\n\")\n      break\n    }\n  } else {\n    consecutive_increases <- 0\n  }\n  \n  prev_bic <- current_bic\n}\n\n# Handle the case where we stopped early\nactual_max <- if(exists(\"i\")) min(i, max_classes) else max_classes\nlca_stats <- lca_stats[1:(actual_max - min_classes + 1), ]\n\n# Select best model based on BIC\nbest_model_idx <- which.min(lca_stats$BIC) + min_classes - 1\ncat(\"\\nBest model based on BIC has\", best_model_idx, \"classes.\\n\")\n\n# Visualize model comparison\nggplot(lca_stats, aes(x = n_classes)) +\n  geom_line(aes(y = BIC, color = \"BIC\")) +\n  geom_point(aes(y = BIC, color = \"BIC\")) +\n  geom_line(aes(y = AIC, color = \"AIC\")) +\n  geom_point(aes(y = AIC, color = \"AIC\")) +\n  labs(title = \"LCA Model Comparison\", \n       x = \"Number of Classes\", \n       y = \"Information Criteria\") +\n  theme_minimal()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# After finding best model\nbest_model <- lca_results[[best_model_idx]]\n\n# 1. Save the entire model object\nsaveRDS(best_model, \"best_lca_model.rds\")\n\n# 2. You might also want to save the class assignments for easier access\nclass_assignments <- apply(best_model$posterior, 1, which.max)\nwrite.csv(data.frame(id = 1:length(class_assignments), \n                    class = class_assignments), \n         \"lca_class_assignments.csv\", row.names = FALSE)\n\n# 3. Save the model comparison statistics\nwrite.csv(lca_stats, \"lca_model_stats.csv\", row.names = FALSE)\n```\n:::\n\n\n\n\n\n### Latent Class Analysis (LCA) Results Summary\n\n#### Model Comparison\n\n| Number of Classes | Log-likelihood | BIC | AIC | G² | X² | Number of Parameters |\n|-------------------|----------------|-----|-----|-----|-----|---------------------|\n| 3 classes         | -342045.2      | 684503.5 | 684166.4 | 8510.915 | 8480.657 | 38 |\n| 4 classes         | -341613.0      | 683780.4 | 683327.9 | 7646.455 | 7608.341 | 51 |\n| 5 classes         | -341273.3      | 683242.4 | 682674.6 | 6967.175 | 6990.710 | 64 |\n| 6 classes         | -340902.5      | 682642.2 | 681959.1 | 6225.598 | 6076.490 | 77 |\n| 7 classes         | -340525.0      | 682028.5 | 681230.1 | 5470.593 | 5492.197 | 90 |\n| 8 classes         | -340291.7      | Not shown | Not shown | Not shown | Not shown | Not shown |\n\nNote: All models display the warning \"MAXIMUM LIKELIHOOD NOT FOUND\".\n\n#### Class Population Distribution\n\n##### 3-Class Model\n- Class 1: 12.24%\n- Class 2: 10.31%\n- Class 3: 77.45%\n\n##### 4-Class Model\n- Class 1: 52.34%\n- Class 2: 28.95%\n- Class 3: 8.51%\n- Class 4: 10.20%\n\n##### 5-Class Model\n- Class 1: 9.79%\n- Class 2: 25.23%\n- Class 3: 11.51%\n- Class 4: 7.32%\n- Class 5: 46.15%\n\n##### 6-Class Model\n- Class 1: 11.63%\n- Class 2: 34.04%\n- Class 3: 7.00%\n- Class 4: 11.14%\n- Class 5: 21.20%\n- Class 6: 15.00%\n\n##### 7-Class Model\n- Class 1: 9.62%\n- Class 2: 40.87%\n- Class 3: 12.53%\n- Class 4: 9.13%\n- Class 5: 7.89%\n- Class 6: 13.21%\n- Class 7: 6.77%\n\n#### Key Variables in the Analysis\n\nThe LCA examined the following categorical variables:\n- Size_cat\n- Floor_cat\n- Green_Index_cat\n- Subway_Dist_cat\n- Pop_Density_cat\n- Median_Age_cat\n\nEach variable was divided into three categories (Pr(1), Pr(2), Pr(3)), and the conditional probabilities for these categories across different latent classes were calculated.\n\n#### Model Selection Insights\n\nThe model fit improves (lower BIC and AIC values) as the number of classes increases. The 7-class model shows the best fit among the fully reported models, with:\n- Log-likelihood: -340525.0\n- BIC: 682028.5\n- AIC: 681230.1\n\nHowever, all models show the warning \"MAXIMUM LIKELIHOOD NOT FOUND,\" which suggests potential convergence issues in the estimation process.\n\n## 4. Parameters and Outputs Determination\n# Variables Selection for Latent Class Analysis\n\n## Primary Variables\n\nFor the latent class analysis model, six categorical variables were selected based on their statistical properties and relevance to property market segmentation:\n\n1. **Size_cat**: Property size categories derived from the continuous variable \"Size\" (ranging from 12.49 to 269.68 square meters). The discretization created balanced categories with 17,374, 17,609, and 17,661 observations across the three groups, providing sufficient data for robust class identification.\n\n2. **Floor_cat**: Floor level categories divided into low (≤5), medium (≤10), and high (>10) floors, resulting in 13,004, 13,234, and 26,406 observations respectively. Though slightly imbalanced toward higher floors, this categorization reflects the actual distribution within the dataset.\n\n3. **Green_Index_cat**: Environmental quality measure (original range: 4.163 to 18.927) categorized into three balanced groups containing 17,374, 17,404, and 17,866 observations, ensuring stable parameter estimation.\n\n4. **Subway_Dist_cat**: Distance to nearest subway station (original range: 3.366 to 9.978) transformed into three approximately equal categories with 17,384, 17,395, and 17,865 observations, providing consistent measurement of accessibility.\n\n5. **Pop_Density_cat**: Population density (original range: 1 to 118,182) discretized into three categories with 17,521, 17,271, and 17,852 observations, offering balanced representation of neighborhood density characteristics.\n\n6. **Median_Age_cat**: Demographic indicator (original range: 32.7 to 55.4) categorized into three groups with 17,670, 18,504, and 16,470 observations, maintaining sufficient data for reliable parameter estimation.\n\nThese variables were retained in the final model as evidenced by their inclusion in the LCA formula:\n\n```\nf <- cbind(Size_cat, Floor_cat, Green_Index_cat, Subway_Dist_cat, Pop_Density_cat, Median_Age_cat) ~ 1\n```\n\n### Model Selection Criteria\nTo determine the optimal number of latent classes, multiple evaluation criteria were employed:\n\n1. **Bayesian Information Criterion (BIC)**: This was established as the primary selection criterion due to its balanced approach to model fit and complexity. BIC imposes a stronger penalty for model complexity compared to AIC, helping to avoid overfitting. In the analysis, BIC values were calculated for models with different class numbers, ranging from 684,503.5 for the 3-class model to 682,028.5 for the 7-class model, with lower values indicating better model fit adjusted for complexity.\n\n2. **Akaike Information Criterion (AIC)**: Used as a secondary criterion, AIC applies a less severe penalty for model complexity. AIC values ranged from 684,166.4 for the 3-class model to 681,230.1 for the 7-class model. The consistent trend in both BIC and AIC provided confidence in model selection decisions.\n\n3. **Entropy**: This measure was used to assess classification quality and certainty. Higher entropy values indicate clearer distinction between classes and more certain classification of observations. An entropy calculation function was implemented to evaluate how well the model separates observations into distinct classes.\n\n4. **Interpretability**: Beyond statistical measures, the substantive interpretability of resulting classes was considered. Classes that represented meaningful and distinct property market segments were valued over purely statistical improvements.\n\n### Class Number Determination Process\nA systematic and comprehensive approach was adopted to determine the optimal number of latent classes:\n\n1. Models with 3 to 8 latent classes were tested sequentially. This range was chosen based on prior research suggesting that fewer than 3 classes would be insufficient to capture market complexity, while more than 8 would likely result in classes too small for meaningful interpretation.\n\n2. For each potential class number, 10 random starts were employed to avoid local maxima in the likelihood function. This approach increases confidence that the global maximum likelihood solution was found for each model specification.\n\n3. An early stopping mechanism was implemented to terminate testing when BIC increased consecutively across two class solutions. This approach follows the principle that when BIC begins to increase consistently, additional classes are likely overfitting the data.\n\n4. Log-likelihood, BIC, and AIC values were carefully tracked across all model iterations to monitor convergence and model fit improvement.\n\n5. The pattern of BIC and AIC decreases was analyzed, with attention to the point where diminishing returns in model fit improvement occurred with increasing class numbers.\n\nBased on this process, the optimal model was determined to be the 6-class solution, which showed substantial improvement in BIC (682,642.2) compared to simpler models while maintaining interpretable and meaningful class structures. While the 7-class model showed a slightly lower BIC (682,028.5), the improvement was marginal and came at the cost of less distinct and less interpretable classes.\n\n### Computational Efficiency Considerations\nSeveral strategies were implemented to enhance computational efficiency while maintaining model quality:\n\n1. Maximum iterations for each model were set to 1,000, striking a balance between ensuring convergence and limiting excessive computation time. This parameter was determined after observing that most models converged well within this limit.\n\n2. Ten random starts were used for each class number to balance between finding the global maximum likelihood and computational time. This number proved sufficient to consistently find the same maximum likelihood solution across multiple runs.\n\n3. The early stopping mechanism based on consecutive BIC increases significantly reduced computation time by avoiding unnecessary exploration of models with poorer fit.\n\n4. A random seed was set to ensure reproducibility while maintaining computational efficiency, allowing for consistent results across repeated analyses.\n\n5. For models with larger numbers of classes, careful monitoring of log-likelihood, BIC, and AIC values across iterations verified proper convergence and solution stability.\n\nThese efficiency considerations allowed for thorough exploration of the model space while ensuring practical computation times, enabling the identification of an optimal latent class solution that effectively captures distinct property market segments.\n\n## 5. UI Component Selection for Shiny Application\n\n### Model Configuration Components for Clustering\n\nFor the Shiny application's clustering functionality using Latent Class Analysis, the following UI components were selected:\n\n- **Number of Clusters Slider**: A simple slider input allowing users to select the desired number of latent classes (3-8). This provides intuitive control while limiting the range to computationally feasible values.\n\n- **Variable Selection Checkboxes**: A set of checkboxes for the six categorical variables (Size_cat, Floor_cat, Green_Index_cat, Subway_Dist_cat, Pop_Density_cat, Median_Age_cat). This allows users to customize which property characteristics to include in their clustering analysis.\n\n- **Run Analysis Button**: A prominent action button that triggers the LCA computation with pre-configured computational parameters (iterations and random starts) set to reasonable defaults behind the scenes.\n\n### Results Visualization Components\n\nThe visualization components focus on clear communication of clustering results:\n\n- **Model Comparison Plot**: A simple line chart showing BIC values across different numbers of classes, helping users visually identify the optimal number of clusters where the line begins to flatten.\n\n- **Cluster Profile Charts**: Bar charts displaying the defining characteristics of each cluster, using color-coding to differentiate between property segments for easy visual comparison.\n\n- **Cluster Summary Table**: A formatted table showing the size of each cluster and its key distinguishing features, giving users a quick overview of the market segmentation.\n\n### User Interaction Design Rationale\n\nThe interface design prioritizes simplicity and guided analysis:\n\n- **Tab-based Organization**: Separate tabs for data upload, cluster analysis, and results interpretation create a natural workflow for users to follow.\n\n- **Simplified Controls**: Technical parameters like maximum iterations and convergence thresholds are preset to optimal values rather than exposed as user controls, reducing complexity.\n\n- **Interpretive Guidance**: Brief explanatory text alongside visualizations helps users understand what the clustering results mean in practical terms.\n\n## 6. Results and Discussion\n\n### Cluster Comparison Analysis\n\nThe LCA clustering explored models with 3 to 8 clusters, with the following key findings:\n\n- **BIC Comparison**: BIC values decreased from 684,503.5 (3-cluster model) to 682,028.5 (7-cluster model), with the rate of improvement slowing after 6 clusters.\n\n- **Optimal Cluster Solution**: The 6-cluster solution (BIC: 682,642.2) provided the best balance between statistical fit and practical interpretability, with clearly differentiated property segments.\n\n- **Cluster Proportions**: The 6-cluster solution identified one large segment (34.04% of properties), four medium-sized segments (ranging from 11.14% to 21.20%), and one smaller niche segment (7.00%).\n\n### Cluster Profiles\n\nThe 6-cluster solution revealed distinct property segments:\n\n- **Cluster 1 (11.63%)**: Large properties on high floors, representing the premium segment of the market with superior space and vertical positioning.\n\n- **Cluster 2 (34.04%)**: Properties with balanced characteristics across all variables, forming the mainstream market segment that appeals to the broadest range of buyers.\n\n- **Cluster 3 (7.00%)**: Medium-sized properties with high environmental quality in dense areas, creating a specialized urban-environmental niche.\n\n- **Cluster 4 (11.14%)**: Medium to large properties with poor subway accessibility, representing areas where space compensates for location disadvantages.\n\n- **Cluster 5 (21.20%)**: Properties in low-density areas with high environmental quality, forming a substantial \"green suburban\" market segment.\n\n- **Cluster 6 (15.00%)**: Smaller properties with excellent subway accessibility, representing the urban convenience segment where location advantages offset size limitations.\n\n### Market Segmentation Applications\n\nThe clustering results provide practical insights for property market analysis:\n\n- The identified clusters offer a data-driven framework for property classification that goes beyond simple price tiers.\n\n- The results reveal important trade-offs defining different market segments: size vs. location, environmental quality vs. density, and floor level vs. accessibility.\n\n- The balanced distribution of cluster sizes indicates diverse market niches beyond the mainstream segment, suggesting opportunities for specialized development.\n\n## 7. Conclusion\n\n### Key Findings\n\nThe LCA clustering successfully identified six distinct property market segments, each with unique characteristic combinations:\n\n1. Premium large, high-floor properties\n2. Mainstream balanced-attribute properties\n3. Urban-environmental properties combining density with green amenities\n4. Spacious but less accessible properties\n5. Green suburban properties with environmental quality and low density\n6. Urban convenience properties with excellent accessibility but limited size\n\n### Applications\n\nThe clustering results provide practical applications for property market analysis:\n\n- Development planning guidance by identifying underserved market segments\n- Improved targeting of marketing messages to specific property buyer segments\n- Better understanding of value drivers across different property types\n\n### Limitations and Future Directions\n\nSome limitations of the current analysis include:\n\n- The discretization of variables into three categories may have simplified some distinctions\n- The exclusion of variables like construction year and socioeconomic indicators\n\nFuture work could enhance the analysis by:\n- Incorporating additional relevant variables\n- Applying the clustering approach to different geographical areas\n- Extending the analysis to include price data to quantify segment premiums\n\nThis structure focuses specifically on the LCA component of your analysis, highlighting the technical implementation aspects while maintaining emphasis on interpretation and practical implications of the results.\n\nLastly, save data into rds format.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(Property_data_lca, \"data/Property_data_lca.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(Property_data, \"data/Property_data.rds\")\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}