project:
  type: website
website:
  title: "ISSS608-Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 0"
            href: hands-on_ex/Hands-on_Ex00.html
          - text: "Hands-on Exercise 1"
            href: hands-on_ex/Hands-on_Ex01.html
          - text: "Hands-on Exercise 2"
            href: hands-on_ex/Hands-on_Ex02.html
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: In-Class_Ex1.html
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex1.html
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
