project:
  type: website
website:
  title: "Xiaohan's visual analytics diary"
  navbar:
    style: "collapsible"
    search: true
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "A Rough First Attempt"
            href: Hands-on_Ex/Hands-on_Ex00.html
          - text: "A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Ex/Hands-on_Ex01.html
          - text: "Beyond ggplot2 Fundamentals"
            href: Hands-on_Ex/Hands-on_Ex02.html
          - text: "Programming Interactive Data Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex03a.html
          - text: "Programming Animated Statistical Graphics with R"
            href: Hands-on_Ex/Hands-on_Ex03b.html
          - text: "Visualising Distribution"
            href: Hands-on_Ex/Hands-on_Ex04a.html
          - text: "Visual Statistical Analysis"
            href: Hands-on_Ex/Hands-on_Ex04b.html
          - text: "Visualising Uncertainty"
            href: Hands-on_Ex/Hands-on_Ex04c.html
          - text: "Building Funnel Plot with R"
            href: Hands-on_Ex/Hands-on_Ex04d.html
          - text: "Creating Ternary Plot with R"
            href: Hands-on_Ex/Hands-on_Ex05a.html
          - text: "Visual Correlation Analysis"
            href: Hands-on_Ex/Hands-on_Ex05b.html
          - text: "Heatmap for Visualising and Analysing Multivariate Data"
            href: Hands-on_Ex/Hands-on_Ex05c.html
          - text: "Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: Hands-on_Ex/Hands-on_Ex05d.html
          - text: "Treemap Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex05e.html
          - text: "Visualising and Analysing Time-oriented Data"
            href: Hands-on_Ex/Hands-on_Ex07.html
          - text: "Choropleth Mapping with R"
            href: Hands-on_Ex/Hands-on_Ex08a.html
          - text: "Visualising Geospatial Point Data"
            href: Hands-on_Ex/Hands-on_Ex08b.html
          - text: "Analytical Mapping"
            href: Hands-on_Ex/Hands-on_Ex08c.html
          - text: "Modelling, Visualising and Analysing Network Data with R"
            href: Hands-on_Ex/Hands-on_Ex09.html
          - text: "Information Dashboard Design: R methods"
            href: Hands-on_Ex/Hands-on_Ex10.html
      - text: "In-Class Exercise"
        menu:
          - text: "In-class Exercise 2025-2-8"
            href: In-class_Ex/In-class_exercise_4/In-class_ex4.html
          - text: "In-class Exercise 2025-3-1"
            href: In-class_Ex/In-class_exercise_7/In-class_ex7.html
          - text: "In-class Exercise 2025-3-22"
            href: In-class_Ex/In-class_exercise_9/In-class_ex9.html
      - text: "Take-home Exercise"
        menu:
          - text: "Ship Performance"
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
          - text: "Singapore International Trade Analysis"
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
          - text: "LCA Model Design"
            href: Take-home_Ex/Take-home_Ex3/Take-home_Ex3a.html
          - text: "MLR Model Design"
            href: Take-home_Ex/Take-home_Ex3/Take-home_Ex3b.html
      - text: "Team Project"
        menu:
          - text: "to be continue"
            href: Take-home_Ex1.html
            
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    css: styles.css
    toc: true
