project:
  type: website
website:
  title: "Xiaohan's visual analytics diary"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "A Rough First Attempt"
            href: Hands-on_Ex/Hands-on_Ex00.html
          - text: "1 A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Ex/Hands-on_Ex01.html
          - text: "2 Beyond ggplot2 Fundamentals"
            href: Hands-on_Ex/Hands-on_Ex02.html
          - text: "3a Programming Interactive Data Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex03a.html
          - text: "3b Programming Animated Statistical Graphics with R"
            href: Hands-on_Ex/Hands-on_Ex03b.html
          - text: "4a Visualising Distribution"
            href: Hands-on_Ex/Hands-on_Ex04a.html
          - text: "4b Visual Statistical Analysis"
            href: Hands-on_Ex/Hands-on_Ex04b.html
          - text: "4c Visualising Uncertainty"
            href: Hands-on_Ex/Hands-on_Ex04c.html
          - text: "4d Building Funnel Plot with R"
            href: Hands-on_Ex/Hands-on_Ex04d.html
          - text: "5a Creating Ternary Plot with R"
            href: Hands-on_Ex/Hands-on_Ex05a.html
          - text: "5b Visual Correlation Analysis"
            href: Hands-on_Ex/Hands-on_Ex05b.html
          - text: "5c Heatmap for Visualising and Analysing Multivariate Data"
            href: Hands-on_Ex/Hands-on_Ex05c.html
          - text: "5d Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: Hands-on_Ex/Hands-on_Ex05d.html
          - text: "5e Treemap Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex05e.html
      - text: "In-Class Exercise"
        menu:
          - text: "In-class Exercise 2025-2-8"
            href: In-class_Ex/In-class_exercise_4/In-class_ex4.html
      - text: "Take-home Exercise"
        menu:
          - text: "Ship Performance"
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
      - text: "Team Project"
        menu:
          - text: "to be continue"
            href: Take-home_Ex1.html
            
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    css: styles.css
    toc: true
