---
title: "In-class Exercise 5"

author: "xh.zhang"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---
# Loading Packages

```{r}
pacman::p_load(tidyverse, readxl, SmartEDA, easystats, gtsummary)
```
# Importing Data

```{r}

library(readxl)
library(dplyr)

```

```{r}

car_resale <- read_excel("data/ToyotaCorolla - Copy.xls")
head(car_resale)
glimpse(car_resale)

```

```{r}
view(car_resale)
```

```{r}
list(car_resale)
```
```{r}
summary(car_resale)
```

# Data Overview

[readxl](https://readxl.tidyverse.org/)

```{r}
car_resale %>%
  ExpData(type = 1)
```

```{r}
car_resale %>%
  ExpData(type = 2)
```


```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin", "Doors", "Gears", "Cylinders", "Fuel_Type", "Color", "ABS", "Airbag_1",
          "Met_Color", "Automatic", "Mfr_Guarantee", "BOVAG_Guarantee", "CD_Player", "Airbag_2", "Airco", "Automatic_airco", 
          "Boardcomputer", "Mistlamps", "Central_Lock", "Powered_Windows", "Power_Steering", "Radio",
          "Sport_Model", "Backseat_Divider", "Metallic_Rim", "Radio_cassette", "Tow_Bar")

car_resale <- read_xls("data/ToyotaCorolla - Copy.xls", sheet = "data") %>%
  mutate(Id = as.character(Id)) %>%
  mutate(across(cols, as.factor))

  
```


```{r}
car_resale %>%
  ExpNumViz(target = NULL,
            col = "#FFB6C1",
            nlim = 10,
            Page = c(2,2))
```


```{r}

car_resale %>%
  ExpNumViz(target = "Price",
            col = "#FFB6C1",
            nlim = 10,
            Page = c(2,2))

```

# Bar plots for all categorical variables

```{r}
#| fig-width: 12
#| fig-height: 10

car_resale %>%
  ExpCatViz(target = NULL,
            col = "#FFB6C1",
            clim = 10,
            margin = 2,
            Page = c(4,4),
            sample = 16)
```
[easystats](https://easystats.github.io/easystats/)

# Checking for Multicollinearity


```{r}
check_collinearity(model)

```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```


```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period, data = car_resale)
model
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + Weight + Guarantee_Period, data = car_resale)

plot (check_normality(model1))

```

```{r}
plot ( check_heteroscedasticity(model1) )
```

# Adding Summary Statistics
[gtsummary](https://www.danieldsjoberg.com/gtsummary/)

```{r}

tbl_regression(model1, intercept = TRUE) %>%
  add_glance_source_note(
    label = list(sigma ~ "\U03C3", adj.r.squared ~ "Adjusted R²"),
    include = c(r.squared, adj.r.squared, AIC, statistic, p.value, sigma)
  )

```


```{r}
summary(model1)
```

```{r}
plot(parameters(model1))
```

```{r}

ggcoefstats(model1,
            output = "plot")
```


