{
  "hash": "7f9315a39aac4460f722f8225cb5f087",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \" \"\nauthor: \"Xiaohan Zhang\"\ndate: \"2025-3-9\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n\n# Background Information\n\n## Task Instructions\n\nDownload the \"Merchandise Trade by Region/Market\" dataset from the Department of Statistics Singapore (DOS) website. Select three data visualizations from DOS \\| SingStat Website - Singapore International Trade, evaluate their strengths and weaknesses, and provide sketches for improved designs. Using ggplot2 and other appropriate R packages, recreate the enhanced versions of the three visualizations. Analyze the data using either time-series analysis or time-series forecasting methods, complementing the analysis with suitable data visualization techniques.\n\n## Reading Guide\n\nIn order to reduce reading costs and highlight the key points, I have removed less important details here and focused on the main aspects of each section, as well as the content I wish to emphasize.\n\nIf detailed explanations are needed, you can refer to the code.\n\n# Set Up the Environment\n\nUse the following code to load the required R packages into the environment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tsibble)\nlibrary(lubridate)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(tidyverse)\nlibrary(patchwork)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(scales)\nlibrary(gridExtra)\nlibrary(tidyr)\nlibrary(readxl)\n\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(ggalluvial)  \nlibrary(scales)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(forecast)\nlibrary(zoo)\nlibrary(tseries)\n```\n:::\n\n\n\n# Learning and Beyond - Modifying Visual Design\n\n## First Image:\n\n### Import Data\n\nI transformed and prepared time series data for three datasets: \"Re_Exports_Monthly.csv,\" \"Imports_Monthly.csv,\" and \"Domestic_Exports_Monthly.csv.\"\n\nFor each dataset, I: 1. Read the CSV file, skipped the first 10 rows, and limited the data to 160 rows. 2. Transposed the data so that rows became columns, and I assigned appropriate column names from the first row. 3. Converted all columns, except for the \"Time\" column, to numeric values. 4. Renamed the \"Data Series\" column to \"Year-Month\" and formatted it to show the year and month. 5. Converted the \"Year-Month\" column to a date format. 6. Transformed the data into a time series object (tsibble) indexed by the \"Year-Month\" column.\n\nFinally, I removed the original datasets to clear the workspace.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRe_Exports <- read_csv(\"data/Re_Exports_Monthly.csv\", \n                        skip = 10,      \n                        n_max = 160)    \n\nRe_Exports_transposed <- as.data.frame(t(Re_Exports))\nRe_Exports_transposed <- rownames_to_column(Re_Exports_transposed, var = \"Time\")\nrownames(Re_Exports_transposed) <- NULL\n\ncolnames(Re_Exports_transposed) <- as.character(Re_Exports_transposed[1, ])\nRe_Exports_transposed <- Re_Exports_transposed[-1, ]\n\nRe_Exports_transposed <- Re_Exports_transposed %>%\n  mutate(across(-1, as.numeric))\n\nRe_Exports_transposed <- Re_Exports_transposed %>%\n  rename(`Year-Month` = `Data Series`) %>%\n  mutate(`Year-Month` = yearmonth(`Year-Month`))\n\nRe_Exports_transposed <- Re_Exports_transposed %>%\n  mutate(`Year-Month` = as.Date(`Year-Month`))\n\nRe_exports_ts <- Re_Exports_transposed %>%\n  as_tsibble(index = `Year-Month`)\n\nrm(Re_Exports, Re_Exports_transposed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nImports <- read_csv(\"data/Imports_Monthly.csv\", \n                        skip = 10,      \n                        n_max = 160)    \n\nImports_transposed <- as.data.frame(t(Imports))\nImports_transposed <- rownames_to_column(Imports_transposed, var = \"Time\")\nrownames(Imports_transposed) <- NULL\n\ncolnames(Imports_transposed) <- as.character(Imports_transposed[1, ])\nImports_transposed <- Imports_transposed[-1, ]\n\nImports_transposed <- Imports_transposed %>%\n  mutate(across(-1, as.numeric))\n\nImports_transposed <- Imports_transposed %>%\n  rename(`Year-Month` = `Data Series`) %>%\n  mutate(`Year-Month` = yearmonth(`Year-Month`))\n\nImports_transposed <- Imports_transposed %>%\n  mutate(`Year-Month` = as.Date(`Year-Month`))\n\nImports_ts <- Imports_transposed %>%\n  as_tsibble(index = `Year-Month`)\n\nrm(Imports, Imports_transposed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nDomestic_Exports <- read_csv(\"data/Domestic_Exports_Monthly.csv\", \n                        skip = 10,      \n                        n_max = 160)    \n\nDomestic_Exports_transposed <- as.data.frame(t(Domestic_Exports))\nDomestic_Exports_transposed <- rownames_to_column(Domestic_Exports_transposed, var = \"Time\")\nrownames(Domestic_Exports_transposed) <- NULL\n\ncolnames(Domestic_Exports_transposed) <- as.character(Domestic_Exports_transposed[1, ])\nDomestic_Exports_transposed <- Domestic_Exports_transposed[-1, ]\n\nDomestic_Exports_transposed <- Domestic_Exports_transposed %>%\n  mutate(across(-1, as.numeric))\n\nDomestic_Exports_transposed <- Domestic_Exports_transposed %>%\n  rename(`Year-Month` = `Data Series`) %>%\n  mutate(`Year-Month` = yearmonth(`Year-Month`))\n\nDomestic_Exports_transposed <- Domestic_Exports_transposed %>%\n  mutate(`Year-Month` = as.Date(`Year-Month`))\n\nDomestic_exports_ts <- Domestic_Exports_transposed %>%\n  as_tsibble(index = `Year-Month`)\n\nrm(Domestic_Exports, Domestic_Exports_transposed)\n```\n:::\n\n\n\n## Modify the First Image\n\n### Organize the Required Data\n\nHere, I need to use import and export data from 2020 to 2024. I will organize the data and name the final dataset as trade_data_2020_2024.\n\nI aggregated and merged data for the years 2020 to 2024 for three variables: Re-Exports, Domestic Exports, and Imports.\n\nFirst, I calculated the annual sum of \"Total All Markets\" for each dataset (Re-Exports, Domestic Exports, and Imports) by year using the `aggregate()` function. I filtered the data for the years between 2020 and 2024, then renamed the resulting columns to reflect the corresponding export or import data for each year.\n\nNext, I merged the three tables by \"Year\" to create a consolidated dataset. I renamed the columns to more descriptive names: \"Domestic_Exports,\" \"Re_Exports,\" and \"Imports.\" I also calculated additional columns: 1. **Total_Exports**, which was the sum of Domestic Exports and Re-Exports. 2. **Trade_Balance**, which was the difference between Total Exports and Imports. 3. **Trade_Balance_YoY**, the year-over-year percentage change in Trade Balance, which I calculated by comparing each year’s trade balance with the previous year.\n\nI formatted the YoY growth rate as a percentage with two decimal places. The first year had no YoY change, so I set it as NA. Finally, I displayed the merged dataset, which included the calculated columns for a clearer understanding of trade dynamics over the period from 2020 to 2024.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nre_exports_by_year <- aggregate(\n  `Total All Markets` ~ year(`Year-Month`), \n  data = subset(Re_exports_ts, year(`Year-Month`) >= 2020 & year(`Year-Month`) <= 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nnames(re_exports_by_year) <- c(\"Year\", \"Re_Exports_by_Year\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nexports_by_year <- aggregate(\n  `Total All Markets` ~ year(`Year-Month`), \n  data = subset(Domestic_exports_ts, year(`Year-Month`) >= 2020 & year(`Year-Month`) <= 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nnames(exports_by_year) <- c(\"Year\", \"Exports_by_Year\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nimports_by_year <- aggregate(\n  `Total All Markets` ~ year(`Year-Month`), \n  data = subset(Imports_ts, year(`Year-Month`) >= 2020 & year(`Year-Month`) <= 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nnames(imports_by_year) <- c(\"Year\", \"Imports_by_Year\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Merge the three tables by Year\ntrade_data_2020_2024 <- merge(exports_by_year, re_exports_by_year, by = \"Year\")\ntrade_data_2020_2024 <- merge(trade_data_2020_2024, imports_by_year, by = \"Year\")\n\n# Rename the table with an English title\nnames(trade_data_2020_2024) <- c(\"Year\", \"Domestic_Exports\", \"Re_Exports\", \"Imports\")\n\n# Calculate total exports (Domestic Exports + Re-Exports)\ntrade_data_2020_2024$Total_Exports <- trade_data_2020_2024$Domestic_Exports + trade_data_2020_2024$Re_Exports\n\n# Calculate trade balance (Total Exports - Imports)\ntrade_data_2020_2024$Trade_Balance <- trade_data_2020_2024$Total_Exports - trade_data_2020_2024$Imports\n\n# Calculate YoY growth rate for Trade Balance\n# Sort by year to ensure correct calculation\ntrade_data_2020_2024 <- trade_data_2020_2024[order(trade_data_2020_2024$Year), ]\n\n# Calculate YoY change for Trade Balance\ntrade_data_2020_2024$Trade_Balance_YoY <- c(NA, \n                                          diff(trade_data_2020_2024$Trade_Balance) / \n                                            abs(trade_data_2020_2024$Trade_Balance[-nrow(trade_data_2020_2024)]) * 100)\n\n# Format YoY as percentage with 2 decimal places\ntrade_data_2020_2024$Trade_Balance_YoY <- sprintf(\"%.2f%%\", trade_data_2020_2024$Trade_Balance_YoY)\n\n# First row will be NA since there's no previous year to compare\ntrade_data_2020_2024$Trade_Balance_YoY[1] <- NA\n\n# Display the merged table\nprint(trade_data_2020_2024)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Year Domestic_Exports Re_Exports  Imports Total_Exports Trade_Balance\n1 2020         234449.6   281195.1 453467.2      515644.7       62177.5\n2 2021         278975.4   335105.6 545881.9      614081.0       68199.1\n3 2022         329668.9   380297.9 655436.0      709966.8       54530.8\n4 2023         285052.8   353350.6 567319.2      638403.4       71084.2\n5 2024         286597.7   387907.3 611359.5      674505.0       63145.5\n  Trade_Balance_YoY\n1              <NA>\n2             9.68%\n3           -20.04%\n4            30.36%\n5           -11.17%\n```\n\n\n:::\n:::\n\n\n\n### Comment on the Original Image\n\n![](images/clipboard-730198914.png)\n\n**Strengths:**\n\n-   Clear color coding with distinct colors for each year\n\n-   Straightforward title that clearly indicates the content (service exports and imports)\n\n-   Direct data labels on the chart make it easy to read specific values\n\n-   Simple structure organizing data by year\n\n-   Bar chart format is appropriate for quantity comparisons\n\n**Weaknesses:**\n\n-   Lacks trade balance information (surplus/deficit)\n\n-   No trend lines to show pattern development over time\n\n-   Limited context about what's driving changes between years\n\n-   No breakdown of service categories to understand composition\n\n-   Horizontally spread layout makes year-to-year comparison less intuitive\n\n### Direction for Modification\n\n-   Add trade balance calculations\n-   Incorporate trend analysis\n-   Segment services by category\n-   Include year-over-year growth metrics\n-   Consider a more comprehensive dashboard approach\n\n### Modified Image\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\n\n# Create a function to calculate year-over-year growth, replacing pct_change\ncalculate_yoy_growth <- function(x) {\n  result <- numeric(length(x))\n  result[1] <- NA  # First value has no YoY comparison, set to NA\n  for (i in 2:length(x)) {\n    if (is.na(x[i]) || is.na(x[i-1]) || x[i-1] == 0) {\n      result[i] <- NA\n    } else {\n      result[i] <- ((x[i] - x[i-1]) / x[i-1]) * 100\n    }\n  }\n  return(result)\n}\n\n\n# Ensure Trade_Balance is numeric, and calculate YoY growth\ntrade_data_2020_2024 <- trade_data_2020_2024 %>%\n  mutate(\n    Trade_Balance = as.numeric(Trade_Balance),\n    Trade_Balance_YoY = calculate_yoy_growth(Trade_Balance)\n  )\n\n# PLOT 2: Exports vs Imports (Now as p1 - first plot)\n# Prepare the data for plotting\n# First, create a long format for the exports (Domestic and Re-exports)\nexports_data <- trade_data_2020_2024 %>%\n  select(Year, Domestic_Exports, Re_Exports) %>%\n  pivot_longer(\n    cols = c(Domestic_Exports, Re_Exports),\n    names_to = \"Category\",\n    values_to = \"Value\"\n  ) %>%\n  mutate(\n    Type = \"Exports\",\n    # Format the category names for better display\n    Category = factor(Category, \n                      levels = c(\"Re_Exports\", \"Domestic_Exports\"),\n                      labels = c(\"Re-Exports\", \"Domestic Exports\"))\n  )\n\n# Create data for imports\nimports_data <- trade_data_2020_2024 %>%\n  select(Year, Imports) %>%\n  rename(Value = Imports) %>%\n  mutate(\n    Type = \"Imports\",\n    Category = \"Imports\"\n  )\n\n# Combine both datasets\ncombined_data <- bind_rows(exports_data, imports_data)\n\n# Convert Year to factor to ensure correct ordering\ncombined_data$Year <- factor(combined_data$Year)\n\n# Create the plot (with slightly smaller text)\np1 <- ggplot(combined_data, aes(x = Type, y = Value, fill = Category)) +\n  geom_col(position = \"stack\") +\n  facet_grid(~ Year) +\n  scale_fill_manual(values = c(\n    \"Domestic Exports\" = \"#ED7D31\",  # Orange\n    \"Re-Exports\" = \"#4472C4\",        # Blue\n    \"Imports\" = \"#A5A5A5\"            # Gray\n  )) +\n  labs(\n    title = NULL,\n    x = NULL,\n    y = \"Value (Million Dollars)\",\n    fill = \"Category\"\n  ) +\n  scale_y_continuous(labels = comma) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    plot.subtitle = element_text(hjust = 0.5, size = 11),\n    axis.text.x = element_text(size = 10, face = \"bold\", angle = 45, hjust = 1),\n    axis.text.y = element_text(size = 9),\n    strip.text = element_text(size = 11, face = \"bold\"),\n    axis.title = element_text(size = 11, face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_text(size = 10),\n    legend.text = element_text(size = 9),\n    panel.grid.major.x = element_blank()\n  )\n\n# PLOT 1: Trade Balance and YoY Growth (Now as p2 - second plot)\n# Transform the data for better visualization\nplot_data <- trade_data_2020_2024 %>%\n  select(Year, Trade_Balance, Trade_Balance_YoY)\n\n# Handle potential NA values\nplot_data <- plot_data %>%\n  mutate(\n    Trade_Balance = if(any(is.na(Trade_Balance))) {\n      replace(Trade_Balance, is.na(Trade_Balance), 0)\n    } else {\n      Trade_Balance\n    }\n  )\n\n# Calculate the scaling factor for the secondary axis\ny_range <- range(plot_data$Trade_Balance, na.rm = TRUE)\ny2_range <- range(plot_data$Trade_Balance_YoY, na.rm = TRUE)\n\n# Prevent cases where y2_range difference is 0 or NA\nif(is.na(diff(y2_range)) || diff(y2_range) == 0) {\n  # If YoY values are all NA or the same, set a default range\n  y2_range <- c(-10, 10)\n}\n\nscale_factor <- diff(y_range) / diff(y2_range)\n\n# Create the dual-axis plot (with slightly smaller text)\np2 <- ggplot(plot_data, aes(x = factor(Year))) +\n  # Trade Balance bars\n  geom_col(aes(y = Trade_Balance, fill = \"Trade Balance\"), \n           width = 0.6, alpha = 0.8) +\n  \n  # Add reference line for YoY 0% at x-axis level\n  geom_hline(yintercept = y_range[1], linetype = \"dashed\", color = \"#ED7D31\", alpha = 0.7) +\n  \n  # YoY growth line (only if there are non-NA values)\n  {if(any(!is.na(plot_data$Trade_Balance_YoY))) \n    geom_line(aes(y = Trade_Balance_YoY * scale_factor + y_range[1], \n                group = 1, color = \"YoY Growth\"), \n            size = 1.2)\n  } +\n  \n  # YoY growth points (only if there are non-NA values)\n  {if(any(!is.na(plot_data$Trade_Balance_YoY)))\n    geom_point(aes(y = Trade_Balance_YoY * scale_factor + y_range[1], \n                 color = \"YoY Growth\"), \n             size = 3)\n  } +\n  \n  # YoY labels on points\n  geom_text(aes(y = Trade_Balance_YoY * scale_factor + y_range[1], \n                label = ifelse(is.na(Trade_Balance_YoY), \"\", \n                               paste0(format(Trade_Balance_YoY, digits = 1), \"%\"))),\n            vjust = -0.8, size = 3, fontface = \"bold\") +\n  \n  # Set colors\n  scale_fill_manual(values = c(\"Trade Balance\" = \"#5B9BD5\")) +\n  scale_color_manual(values = c(\"YoY Growth\" = \"#ED7D31\")) +\n  \n  # Primary y-axis (Trade Balance)\n  scale_y_continuous(\n    name = \"Trade Balance (Million Dollars)\",\n    labels = comma,\n    sec.axis = sec_axis(~ (. - y_range[1]) / scale_factor, \n                         name = \"YoY Growth (%)\")\n  ) +\n  \n  # Add title and labels\n  labs(title = NULL,\n       x = \"Year\") +\n  \n  # Customize theme\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 14, face = \"bold\"),\n    axis.text.x = element_text(size = 10, face = \"bold\", angle = 45, hjust = 1),\n    axis.text.y = element_text(size = 9),\n    axis.title = element_text(size = 11, face = \"bold\"),\n    axis.title.y.left = element_text(color = \"#5B9BD5\", face = \"bold\"),\n    axis.title.y.right = element_text(color = \"#ED7D31\", face = \"bold\"),\n    legend.position = \"bottom\",\n    legend.title = element_blank(),\n    legend.text = element_text(size = 9),\n    panel.grid.major.x = element_blank()\n  ) +\n  \n  # Adjust legend\n  guides(fill = guide_legend(order = 1), \n         color = guide_legend(order = 2))\n\n# Combine the two plots side by side with one main title\n# Adjusted to swap the order of plots (Exports/Imports first, then Trade Balance)\ngrid.arrange(p1, p2, ncol = 2, widths = c(1.2, 1), \n             top = grid::textGrob(\"Trade Data Analysis (2020-2024)\", \n                                 gp = grid::gpar(fontsize = 16, fontface = \"bold\")))\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n![](images/clipboard-2429699134.png)\n\nThe right panel addresses a key weakness of the original chart by explicitly showing trade balance trends and year-over-year growth. The dramatic fluctuation in YoY growth - particularly the 30% surge in 2023 followed by an 11% contraction in 2024 - highlights potential volatility in the trading environment.\n\nWhat's particularly revealing is the trade balance pattern from 2020-2024. After maintaining a positive trajectory through 2021, the sharp 20% decline in 2022 suggests a significant market disruption, possibly related to supply chain issues or changing global demand patterns. The remarkable recovery in 2023 (+30%) indicates exceptional resilience, perhaps through policy interventions or market adaptation.\n\nThe consistent trade surplus throughout the period demonstrates overall competitive strength in services, but the declining balance in 2024 despite maintained export levels signals potential challenges in cost management or shifting competitive dynamics.\n\n# Second Image:\n\n## Import Data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMerchandise_Trade_By_Commodity <- read_excel(\"data/Merchandise_Trade_By_Commodity_Section_Current_Prices_Monthly.xlsx\")    \n```\n:::\n\n\n\n### Organize the Required Data\n\nI began by transposing the `Merchandise_Trade_By_Commodity` dataset to organize the data more effectively. After transposing, I added the time variable as a new column and removed the row names to ensure proper structuring. I then renamed the columns, converting them to characters, and removed the first row that was unnecessary for analysis.\n\nNext, I converted the relevant columns to numeric values to facilitate further analysis. I renamed the time column to `Year-Month` and ensured it was in the correct date format. After that, I converted the data to a time series object (`tsibble`) using the `Year-Month` as the index.\n\nFor the year 2024, I aggregated the data by summing the values for each category and removed unnecessary columns to focus on relevant variables, such as imports and exports of chemicals, manufactured goods, machinery, and miscellaneous manufactured articles. I renamed the column for the year to make it clearer.\n\nI then created a new dataset (`trade_data`) by selecting specific columns related to imports and exports for the year 2024. I rounded the values in millions to improve readability.\n\nI also calculated the \"Other Imports\" and \"Other Exports\" by subtracting the sum of specific categories (e.g., chemicals, manufactured goods) from the total imports and exports.\n\nFinally, I prepared a new dataset (`flow_data`) to visualize the data in terms of imports and exports. I calculated the percentage contribution of each category to total imports and exports. I also ordered the categories for exports in descending order to provide a more insightful presentation of the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMerchandise_Trade_By_Commodity_transposed <- as.data.frame(t(Merchandise_Trade_By_Commodity))\nMerchandise_Trade_By_Commodity_transposed <- rownames_to_column(Merchandise_Trade_By_Commodity_transposed, var = \"Time\")\nrownames(Merchandise_Trade_By_Commodity_transposed) <- NULL\n\ncolnames(Merchandise_Trade_By_Commodity_transposed) <- as.character(Merchandise_Trade_By_Commodity_transposed[1, ])\nMerchandise_Trade_By_Commodity_transposed <- Merchandise_Trade_By_Commodity_transposed[-1, ]\n\nMerchandise_Trade_By_Commodity_transposed <- Merchandise_Trade_By_Commodity_transposed %>%\n  mutate(across(-1, as.numeric))\n\nMerchandise_Trade_By_Commodity_transposed <- Merchandise_Trade_By_Commodity_transposed %>%\n  rename(`Year-Month` = `Data Series`) %>%\n  mutate(`Year-Month` = yearmonth(`Year-Month`))\n\nMerchandise_Trade_By_Commodity_transposed <- Merchandise_Trade_By_Commodity_transposed %>%\n  mutate(`Year-Month` = as.Date(`Year-Month`))\n\nMerchandise_Trade_By_Commodity_ts <- Merchandise_Trade_By_Commodity_transposed %>%\n  as_tsibble(index = `Year-Month`)\n\nrm(Merchandise_Trade_By_Commodity, Merchandise_Trade_By_Commodity_transposed)\n\nMerchandise_Trade_By_Commodity_year <- aggregate(. ~ year(`Year-Month`), \n  data = subset(Merchandise_Trade_By_Commodity_ts, year(`Year-Month`) == 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nMerchandise_Trade_By_Commodity_year <- Merchandise_Trade_By_Commodity_year %>%\n  select(-`Year-Month`) %>% \n  rename(Year = `year(\\`Year-Month\\`)`)  \n\n\ntrade_data <- Merchandise_Trade_By_Commodity_year %>%\n  filter(Year == 2024) %>%\n  select(\n    Year,\n    Chemicals_Products_Imports = `Chemicals & Chemical Products_Imports`,\n    Chemicals_Products_Exports = `Chemicals & Chemical Products_Exports`,\n    Manufactured_Goods_Imports = `Manufactured Goods_Imports`,\n    Manufactured_Goods_Exports = `Manufactured Goods_Exports`,\n    Machinery_Transport_Imports = `Machinery & Transport Equipment_Imports`,\n    Machinery_Transport_Exports = `Machinery & Transport Equipment_Exports`,\n    Misc_Manufactured_Imports = `Miscellaneous Manufactured Articles_Imports`,\n    Misc_Manufactured_Exports = `Miscellaneous Manufactured Articles_Exports`,\n    Non_Oil_Imports, \n    Non_Oil_Exports\n  )\n\n\ntrade_bil <- trade_data\ncols_to_convert <- colnames(trade_bil)[-1]  \ntrade_bil[cols_to_convert] <- lapply(trade_bil[cols_to_convert], function(x) round(x / 1e6, 1))\n\ntrade_bil$Other_Imports <- trade_bil$Non_Oil_Imports - \n                         (trade_bil$Chemicals_Products_Imports + \n                          trade_bil$Manufactured_Goods_Imports + \n                          trade_bil$Machinery_Transport_Imports + \n                          trade_bil$Misc_Manufactured_Imports)\n\ntrade_bil$Other_Exports <- trade_bil$Non_Oil_Exports - \n                         (trade_bil$Chemicals_Products_Exports + \n                          trade_bil$Manufactured_Goods_Exports + \n                          trade_bil$Machinery_Transport_Exports + \n                          trade_bil$Misc_Manufactured_Exports)\n\n\nflow_data <- data.frame(\n  Direction = c(rep(\"Import\", 5), rep(\"Export\", 5)),\n  Category = rep(c(\"Machinery & Transport Equipment\", \n                   \"Chemicals & Chemical Products\",\n                   \"Misc. Manufactured Articles\",\n                   \"Manufactured Goods\",\n                   \"Other Categories\"), 2),\n  Value_Bil = c(\n    trade_bil$Machinery_Transport_Imports,\n    trade_bil$Chemicals_Products_Imports,\n    trade_bil$Misc_Manufactured_Imports,\n    trade_bil$Manufactured_Goods_Imports,\n    trade_bil$Other_Imports,\n    trade_bil$Machinery_Transport_Exports,\n    trade_bil$Chemicals_Products_Exports,\n    trade_bil$Misc_Manufactured_Exports,\n    trade_bil$Manufactured_Goods_Exports,\n    trade_bil$Other_Exports\n  )\n)\n\nflow_data <- flow_data %>%\n  group_by(Direction) %>%\n  mutate(Percentage = round(Value_Bil / sum(Value_Bil) * 100, 1)) %>%\n  ungroup()\n\nflow_data$Category <- factor(\n  flow_data$Category,\n  levels = flow_data %>%\n    filter(Direction == \"Export\") %>%\n    arrange(desc(Value_Bil)) %>%\n    pull(Category)\n)\n```\n:::\n\n\n\n### Comment on the Original Image\n\n![](images/clipboard-2209624203.png)\n\nStrengths:\n\nClean horizontal bar chart design with intuitive left-to-right reading pattern Clear category labeling with illustrative icons for easier identification Distinct color coding differentiating exports (orange) and imports (blue) Direct value labeling showing both monetary amounts and percentage contributions Logical organization by category size making dominant sectors immediately visible Consistent formatting and proportional bars allowing for direct visual comparison\n\nWeaknesses:\n\nNo visualization of trade balances (surplus/deficit) for each commodity section Linear presentation obscures flow relationships between imports and exports Equal visual space allocated to minor categories despite vast differences in importance Lack of visual hierarchy to emphasize most economically significant categories No integrated visualization showing overall import-export relationship Limited context about how categories connect in the broader trade ecosystem\n\n### Direction for Modification\n\nTransform the visualization into a flow-based diagram that shows the relationships between export and import categories Use a Sankey diagram approach to visualize the magnitude and direction of trade flows Emphasize proportionality through width of flow channels to better represent economic significance Integrate both sides of trade (exports and imports) into a unified visual system Focus visual attention on major categories while still representing the complete dataset Create a more intuitive representation of trade balances through flow visualization\n\n### Modified Image\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create custom color scheme\nmy_colors <- c(\n  \"Machinery & Transport Equipment\" = \"#1F77B4\",\n  \"Chemicals & Chemical Products\" = \"#FF7F0E\",\n  \"Misc. Manufactured Articles\" = \"#2CA02C\",\n  \"Manufactured Goods\" = \"#D62728\",\n  \"Other Categories\" = \"#9467BD\"\n)\n\n# Create an alluvial-like diagram (similar to a Sankey diagram)\nggplot(flow_data, \n       aes(y = Value_Bil, axis1 = Direction, axis2 = Category)) +\n  # Add alluvial layers\n  geom_alluvium(aes(fill = Category), width = 0.4, alpha = 0.8) +\n  \n  # Add labels to the flows\n  geom_text(\n    stat = \"alluvium\",\n    aes(label = paste0(\"S$\", Value_Bil, \" Bil\\n(\", Percentage, \"%)\")),\n    size = 3.2, color = \"white\", fontface = \"bold\"\n  ) +\n  \n  # Add axes\n  geom_stratum(width = 0.3, fill = \"white\", color = \"grey\") +\n  geom_text(stat = \"stratum\", aes(label = after_stat(stratum)), size = 3.5) +\n  \n  # Apply custom color scheme\n  scale_fill_manual(values = my_colors) +\n  \n  # Format Y-axis\n  scale_y_continuous(\n    labels = function(x) paste0(\"S$\", x, \" Bil\"),\n    expand = expansion(mult = c(0, 0.1))  # Add space at the top\n  ) +\n  \n  # Apply professional theme\n  theme_minimal() +\n  theme(\n    # Grid lines\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor = element_blank(),\n    \n    # Text style\n    axis.text.y = element_text(size = 10),\n    axis.text.x = element_text(face = \"bold\", size = 12),\n    axis.title = element_blank(),\n    \n    # Legend style\n    legend.title = element_blank(),\n    legend.position = \"bottom\",\n    legend.text = element_text(size = 10),\n    \n    # Title style\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(b = 15)),\n    plot.caption = element_text(size = 8, hjust = 1, margin = margin(t = 15)),\n    \n    # Background\n    plot.background = element_rect(fill = \"white\", color = NA),\n    panel.background = element_rect(fill = \"white\", color = NA),\n    \n    # Margins\n    plot.margin = margin(t = 30, r = 20, b = 20, l = 20)\n  ) +\n  \n  # Add informative labels\n  labs(\n    title = \"NON-OIL MERCHANDISE TRADE FLOWS BY CATEGORY\",\n    subtitle = \"2024 - Import and Export Flows\")\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n![](images/clipboard-3351275015.png)\n\nThe visualization immediately communicates the overwhelming dominance of Machinery & Transport Equipment, which constitutes approximately 65% of both export and import activity. However, the flow diagram reveals something the original chart couldn't: despite similar proportional representation on both sides, this sector generates a substantial positive trade balance, serving as the primary engine of the country's trade surplus. The diagram exposes critical structural imbalances across categories. While Machinery and Chemicals establish strong positive trade balances, Manufactured Goods show a significant deficit. This pattern suggests an economy specialized in capital equipment and chemical production but dependent on imported consumer goods - possibly indicating advanced industrial capabilities but underdeveloped consumer goods manufacturing. The visual representation highlights the concerning concentration of export value in just three categories (Machinery, Chemicals, and Miscellaneous Manufactured Articles), which collectively represent nearly 90% of export revenue. This concentration points to potential economic vulnerability should global demand shift in these specific sectors, a risk factor completely obscured in the original chart.\n\n## Third Image\n\n### Import Data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDomestic_Exports_By_Commodity <- read_excel(\"data/Domestic_Exports_By_Commodity_Division_Monthly.xlsx\")    \n```\n:::\n\n\n\n### Organize the Required Data\n\nI worked on transforming and analyzing data related to domestic exports by commodity. First, I transposed the dataset and converted it into a proper format, making the time variable more accessible. I ensured that the \"Year-Month\" column was correctly formatted by converting it into a date type and then created a time series object for further analysis.\n\nI then aggregated the data by year, specifically focusing on 2024, summing up the values for each commodity. After that, I reshaped the dataset into a long format, making it easier to work with different commodity groups. I categorized the commodities into specific groups, such as Food and Agriculture, Raw Materials, Energy Products, and others, based on predefined criteria.\n\nOnce the commodities were grouped, I summarized the data by calculating the total value for each group and the percentage contribution of each group to the total export value. I then arranged the groups in descending order based on their total export value.\n\nFinally, I created a new dataset, `Domestic_Exports_By_Group`, which contained the summarized export data for each commodity group. This dataset provided insights into the major export groups and their relative contributions, laying the foundation for further analysis or visualization.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDomestic_Exports_By_Commodity_transposed <- as.data.frame(t(Domestic_Exports_By_Commodity))\nDomestic_Exports_By_Commodity_transposed <- rownames_to_column(Domestic_Exports_By_Commodity_transposed, var = \"Time\")\nrownames(Domestic_Exports_By_Commodity_transposed) <- NULL\n\ncolnames(Domestic_Exports_By_Commodity_transposed) <- as.character(Domestic_Exports_By_Commodity_transposed[1, ])\nDomestic_Exports_By_Commodity_transposed <- Domestic_Exports_By_Commodity_transposed[-1, ]\n\nDomestic_Exports_By_Commodity_transposed <- Domestic_Exports_By_Commodity_transposed %>%\n  mutate(across(-1, as.numeric))\n\nDomestic_Exports_By_Commodity_transposed <- Domestic_Exports_By_Commodity_transposed %>%\n  rename(`Year-Month` = `Data Series`) %>%\n  mutate(`Year-Month` = yearmonth(`Year-Month`))\n\nDomestic_Exports_By_Commodity_transposed <- Domestic_Exports_By_Commodity_transposed %>%\n  mutate(`Year-Month` = as.Date(`Year-Month`))\n\nDomestic_Exports_By_Commodity_ts <- Domestic_Exports_By_Commodity_transposed %>%\n  as_tsibble(index = `Year-Month`)\n\nrm(Domestic_Exports_By_Commodity, Domestic_Exports_By_Commodity_transposed)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nDomestic_Exports_By_Commodity_year <- aggregate(. ~ year(`Year-Month`), \n  data = subset(Domestic_Exports_By_Commodity_ts, year(`Year-Month`) == 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nDomestic_Exports_By_Commodity_year <- Domestic_Exports_By_Commodity_year %>%\n  select(-`Year-Month`) %>%   \n  rename(Year = `year(\\`Year-Month\\`)`) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncommodity_cols <- names(Domestic_Exports_By_Commodity_year)[\n  !names(Domestic_Exports_By_Commodity_year) %in% \n    c(\"Year\", \"Total Domestic Exports\", \"commodity_group\")\n]\n\nDomestic_Exports_Long <- pivot_longer(\n  Domestic_Exports_By_Commodity_year,\n  cols = all_of(commodity_cols),\n  names_to = \"commodity\",\n  values_to = \"value\"\n)\n\n\nDomestic_Exports_Long$commodity_group <- NA\n\n# Food and Agriculture\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Fish, Seafood (Excl Marine Mammals) & Preparations\",\n    \"Cereals & Cereal Preparations\",\n    \"Vegetables & Fruit\",\n    \"Coffee, Tea, Cocoa, Spices & Manufactures\",\n    \"Beverages\",\n    \"Tobacco & Manufactures\",\n    \"Crude Animal & Vegetable Materials Nes\"\n  )\n] <- \"Food and Agriculture\"\n\n# Raw Materials\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Crude Rubber\",\n    \"Crude Fertilizers & Minerals (Excl Division 56 Coal Petroleum & Precious Stones)\",\n    \"Metalliferous Ores & Metal Scrap\"\n  )\n] <- \"Raw Materials\"\n\n# Energy Products\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Coal, Coke & Briquettes\",\n    \"Petroleum & Products & Related Materials\",\n    \"Gas\",\n    \"Oil Bunkers\"\n  )\n] <- \"Energy Products\"\n\n# Oils and Fats\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Fixed Vegetable Fats & Oils Crude Refined Or Fractionated\",\n    \"Animal Or Vegetable Fats & Oils Processed Waxes Of Animal Or Vegetable Origin Inedible Mixtures Or Preparations Of Animal Or Vegetable Fats Or Oils Nes\"\n  )\n] <- \"Oils and Fats\"\n\n# Chemicals and Pharmaceuticals\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Organic Chemicals\",\n    \"Medicinal & Pharmaceutical Products\",\n    \"Essential Oils & Resinoids & Perfume Materials; Toilet Polishing & Cleansing Preparations\",\n    \"Plastics In Primary Forms\",\n    \"Plastics In Non-Primary Forms\",\n    \"Rubber Manufactures Nes\"\n  )\n] <- \"Chemicals and Pharmaceuticals\"\n\n# Manufacturing Supplies\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Paper, Paperboard & Articles Of Paper Pulp Of Paper Or Of Paperboard\",\n    \"Textile, Yarn, Fabrics Made-Up Articles Nes & Related Products\",\n    \"Non-Metallic Mineral Manufactures Nes\"\n  )\n] <- \"Manufacturing Supplies\"\n\n# Metals\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Iron & Steel\",\n    \"Non-Ferrous Metals\",\n    \"Manufactures Of Metals Nes\"\n  )\n] <- \"Metals\"\n\n# Machinery and Electronics\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Office Machines & Automatic Data-Processing Machines\",\n    \"Telecommunications & Sound-Recording & Reproducing Apparatus & Equipment\",\n    \"Electrical Machinery Apparatus & Appliances Nes & Electrical Parts Thereof\"\n  )\n] <- \"Machinery and Electronics\"\n\n# Consumer Goods\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Articles Of Apparel & Clothing Accessories\"\n  )\n] <- \"Consumer Goods\"\n\n# Precision Instruments and Misc Manufacturing\nDomestic_Exports_Long$commodity_group[\n  Domestic_Exports_Long$commodity %in% c(\n    \"Professional Scientific & Controlling Instruments & Apparatus Nes\",\n    \"Photographic Apparatus Equipment & Supplies & Optical Goods Nes; Watches & Clocks\",\n    \"Miscellaneous Manufactured Articles Nes\"\n  )\n] <- \"Precision Instruments\"\n\n\n\nexport_by_group <- Domestic_Exports_Long %>%\n  group_by(commodity_group) %>%\n  summarize(value = sum(value, na.rm = TRUE)) %>%\n  ungroup() %>%\n  filter(!is.na(commodity_group))  \n\ntotal_value <- sum(export_by_group$value)\n\n\nexport_by_group <- export_by_group %>%\n  mutate(percentage = value / total_value * 100) %>%\n  arrange(desc(value))\n\n\nexport_by_group$commodity_group <- factor(\n  export_by_group$commodity_group,\n  levels = export_by_group$commodity_group[order(-export_by_group$value)]\n)\n\n\nDomestic_Exports_By_Group <- export_by_group\n```\n:::\n\n\n\n### Comment on the Original Image\n\n![](images/clipboard-2517275851.png)\n\n**Strengths:**\n\n-   Visually engaging Sankey diagram approach showing the flow of exports by category\n\n-   Creative design with nautical theme connecting to international trade concept\n\n-   Clear icons representing each commodity group enhance recognition\n\n-   Direct labeling of monetary values and percentage contributions\n\n-   Color-coded flows help track connections between categories\n\n-   Proportional visualization of relative importance through width of flows\n\n**Weaknesses:**\n\n-   Unconventional layout may require learning curve for some viewers\n\n-   Complex flow paths sometimes cross or overlap, potentially creating confusion\n\n-   Vertical orientation makes precise value comparison between categories difficult\n\n-   Limited context about overall export patterns or key insights\n\n-   Some small-value categories are difficult to distinguish visually\n\n-   Background elements might distract from the data presentation\n\n### Direction for Modification\n\n-   Transform into a treemap visualization to clearly show hierarchical relationships\n\n<!-- -->\n\n-   Create distinct size-proportional blocks for immediate visual comparison\n\n<!-- -->\n\n-   Implement a more organized layout with strategic nesting of related categories\n\n<!-- -->\n\n-   Focus on clear, direct value labeling within each category block\n\n<!-- -->\n\n-   Use a consistent color scheme that enhances category differentiation\n\n<!-- -->\n\n-   Simplify the design to focus attention on the data rather than decorative elements\n\n### Modified Image\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(ggplot2)\nlibrary(treemapify)\nlibrary(dplyr)\nlibrary(scales) # For better formatting\n\n# Assuming Domestic_Exports_By_Group dataframe exists with columns:\n# commodity_group, value, percentage\n\n# Create a professional color palette for different commodity groups\ngroup_colors <- c(\n  \"Energy Products\" = \"#2C7BB6\",\n  \"Machinery and Electronics\" = \"#D7301F\",\n  \"Chemicals and Pharmaceuticals\" = \"#1A9850\",\n  \"Precision Instruments\" = \"#756BB1\",\n  \"Metals\" = \"#FD8D3C\",\n  \"Raw Materials\" = \"#31A354\",\n  \"Food and Agriculture\" = \"#FDCC8A\",\n  \"Manufacturing Supplies\" = \"#636363\",\n  \"Consumer Goods\" = \"#FFFFBF\",\n  \"Oils and Fats\" = \"#8C96C6\"\n)\n\n# Create the treemap with enhanced professional styling\ntreemap_plot <- ggplot(Domestic_Exports_By_Group, \n                      aes(area = value, \n                          fill = commodity_group, \n                          label = paste0(commodity_group, \"\\n\", \n                                        dollar(value/1e6, suffix = \"M\", prefix = \"$\"), \n                                        \"\\n\", \n                                        percent(percentage/100, accuracy = 0.1)))) +\n  geom_treemap(color = \"white\", size = 0.5) +\n  geom_treemap_text(colour = \"white\", \n                   place = \"centre\",\n                   size = 8,\n                   fontface = \"bold\",\n                   min.size = 6,\n                   grow = TRUE) +\n  scale_fill_manual(values = group_colors) +\n  labs(title = \"Export Commodity Group Composition\",\n       subtitle = \"By Export Value in USD Million\") +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", size = 16, hjust = 0.5),\n    plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(b = 20)),\n    plot.caption = element_text(size = 8, hjust = 1, margin = margin(t = 10)),\n    plot.background = element_rect(fill = \"white\", color = NA),\n    plot.margin = margin(20, 20, 20, 20)\n  )\n\n# To add a proper border around the entire visualization\ntreemap_plot <- treemap_plot +\n  coord_cartesian(clip = \"off\") +\n  annotate(\"rect\", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf,\n           color = \"gray80\", fill = NA, size = 0.5)\n\n# Display the treemap\nprint(treemap_plot)\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n![](images/clipboard-2180073597.png)\n\nMost notable in the visualization is the dominant position of Energy Products, comprising 49.7% of all export value at \\$113 million. This significant concentration indicates a heavy reliance on energy exports as a key economic driver, which could create vulnerability to fluctuations in global energy markets. The large visual block representing this category effectively illustrates this concentration in a way that numbers alone cannot convey.\n\nThe visualization also shows a fairly balanced distribution across three secondary export categories: Machinery and Electronics (17.1%), Chemicals and Pharmaceuticals (16.5%), and Precision Instruments (12.4%). When combined with Energy Products, these four categories account for 95.7% of total export value, demonstrating a highly specialized export economy. The nested elements within these categories provide further detail about subcategory composition.\n\nThe treemap reveals minimal contributions from traditional sectors such as Food and Agriculture (1.0%) and Raw Materials (1.1%), suggesting an economy that has moved away from primary production toward higher-value manufacturing and energy exports. This composition indicates an advanced stage of economic development but also potential vulnerability to disruptions in specific sectors.\n\n## Time-Series Analysis\n\n### Organize the Required Data\n\nI worked on processing and analyzing trade data from 2015 to 2024, focusing on domestic exports, re-exports, and imports. I began by aggregating the data monthly for each category, creating separate datasets for re-exports, domestic exports, and imports, and then merging them into a single dataset. I calculated the total exports and trade balance, and derived the month-over-month percentage change for the trade balance.\n\nNext, I adjusted the dataset by ensuring the correct date format, renaming columns for clarity, and sorting the data by date. I split the data into three periods: pre-COVID, during COVID, and post-COVID. I also created time series objects for total exports, segmenting the data by these periods.\n\nFor each period, I calculated the mean and standard deviation of total exports to compare the trends across the different phases of the pandemic. This allowed me to assess the impact of COVID-19 on trade performance by analyzing the differences in export values before, during, and after the pandemic.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreexp_monthly <- aggregate(\n  `Total All Markets` ~ format(`Year-Month`, \"%Y-%m-01\"), \n  data = subset(Re_exports_ts, year(`Year-Month`) >= 2015 & year(`Year-Month`) <= 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nnames(reexp_monthly) <- c(\"Date_YM\", \"ReExp_Value\")\nreexp_monthly$Date_YM <- as.Date(reexp_monthly$Date_YM)\n\ndomexp_monthly <- aggregate(\n  `Total All Markets` ~ format(`Year-Month`, \"%Y-%m-01\"), \n  data = subset(Domestic_exports_ts, year(`Year-Month`) >= 2015 & year(`Year-Month`) <= 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nnames(domexp_monthly) <- c(\"Date_YM\", \"DomExp_Value\")\ndomexp_monthly$Date_YM <- as.Date(domexp_monthly$Date_YM)\n\nimp_monthly <- aggregate(\n  `Total All Markets` ~ format(`Year-Month`, \"%Y-%m-01\"), \n  data = subset(Imports_ts, year(`Year-Month`) >= 2015 & year(`Year-Month`) <= 2024), \n  FUN = function(x) sum(x, na.rm = TRUE)\n)\n\nnames(imp_monthly) <- c(\"Date_YM\", \"Import_Value\")\nimp_monthly$Date_YM <- as.Date(imp_monthly$Date_YM)\n\ntrade_data_longterm <- merge(domexp_monthly, reexp_monthly, by = \"Date_YM\")\ntrade_data_longterm <- merge(trade_data_longterm, imp_monthly, by = \"Date_YM\")\n\ntrade_data_longterm$Total_Exp_Value <- trade_data_longterm$DomExp_Value + trade_data_longterm$ReExp_Value\n\ntrade_data_longterm$Trade_Bal <- trade_data_longterm$Total_Exp_Value - trade_data_longterm$Import_Value\n\ntrade_data_longterm <- trade_data_longterm[order(trade_data_longterm$Date_YM), ]\n\ntrade_data_longterm$Trade_Bal_MoM_Pct <- c(NA, \n                                    diff(trade_data_longterm$Trade_Bal) / \n                                    abs(trade_data_longterm$Trade_Bal[-nrow(trade_data_longterm)]) * 100)\n\ntrade_data_longterm$Trade_Bal_MoM_Pct <- round(trade_data_longterm$Trade_Bal_MoM_Pct, 2)\n\nprint(trade_data_longterm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Date_YM DomExp_Value ReExp_Value Import_Value Total_Exp_Value Trade_Bal\n1   2015-01-01      19921.7     22758.0      35221.2         42679.7    7458.5\n2   2015-02-01      16622.1     18123.2      29731.2         34745.3    5014.1\n3   2015-03-01      23159.6     23181.9      38824.7         46341.5    7516.8\n4   2015-04-01      20829.5     21296.6      36970.4         42126.1    5155.7\n5   2015-05-01      19637.1     19782.4      33572.4         39419.5    5847.1\n6   2015-06-01      21109.2     20215.5      36614.8         41324.7    4709.9\n7   2015-07-01      21909.5     20974.2      37430.9         42883.7    5452.8\n8   2015-08-01      18999.3     19500.2      35260.5         38499.5    3239.0\n9   2015-09-01      19701.7     20865.1      35279.0         40566.8    5287.8\n10  2015-10-01      20189.5     23283.6      35998.1         43473.1    7475.0\n11  2015-11-01      17321.0     21831.0      33630.6         39152.0    5521.4\n12  2015-12-01      18332.7     22271.5      34868.8         40604.2    5735.4\n13  2016-01-01      16643.9     19730.3      30382.9         36374.2    5991.3\n14  2016-02-01      15024.3     17368.4      30949.9         32392.7    1442.8\n15  2016-03-01      17947.9     20872.1      33662.0         38820.0    5158.0\n16  2016-04-01      18822.0     19955.0      32238.0         38777.0    6539.0\n17  2016-05-01      20068.4     18839.2      32922.4         38907.6    5985.2\n18  2016-06-01      19591.8     19711.2      34067.9         39303.0    5235.1\n19  2016-07-01      18547.8     19615.4      31906.4         38163.2    6256.8\n20  2016-08-01      18194.4     20433.6      33527.9         38628.0    5100.1\n21  2016-09-01      19014.9     20674.6      32761.0         39689.5    6928.5\n22  2016-10-01      18278.5     21367.3      33929.8         39645.8    5716.0\n23  2016-11-01      20283.0     21606.0      37483.0         41889.0    4406.0\n24  2016-12-01      21516.2     22805.3      39473.3         44321.5    4848.2\n25  2017-01-01      20404.3     19991.2      36734.9         40395.5    3660.6\n26  2017-02-01      20545.0     18795.3      33032.6         39340.3    6307.7\n27  2017-03-01      23098.2     22974.5      39987.6         46072.7    6085.1\n28  2017-04-01      20736.5     19694.5      34542.1         40431.0    5888.9\n29  2017-05-01      22282.2     21663.0      39149.5         43945.2    4795.7\n30  2017-06-01      21088.2     21236.0      36416.6         42324.2    5907.6\n31  2017-07-01      19856.1     22773.3      36874.7         42629.4    5754.7\n32  2017-08-01      21594.6     22870.2      38702.9         44464.8    5761.9\n33  2017-09-01      20428.5     20750.2      35732.2         41178.7    5446.5\n34  2017-10-01      22545.5     21194.1      39347.1         43739.6    4392.5\n35  2017-11-01      23434.9     22451.3      41477.0         45886.2    4409.2\n36  2017-12-01      23287.9     21305.3      40104.3         44593.2    4488.9\n37  2018-01-01      23207.3     20919.2      38491.5         44126.5    5635.0\n38  2018-02-01      20113.2     18823.2      34609.6         38936.4    4326.8\n39  2018-03-01      22997.9     22604.3      39745.5         45602.2    5856.7\n40  2018-04-01      23078.8     21413.4      38382.7         44492.2    6109.5\n41  2018-05-01      25908.0     22451.7      42887.8         48359.7    5471.9\n42  2018-06-01      23385.7     22308.1      41054.6         45693.8    4639.2\n43  2018-07-01      23569.5     24737.2      44972.5         48306.7    3334.2\n44  2018-08-01      24732.0     25716.6      43802.1         50448.6    6646.5\n45  2018-09-01      22549.9     23300.4      41439.6         45850.3    4410.7\n46  2018-10-01      26021.8     25634.6      47127.1         51656.4    4529.3\n47  2018-11-01      24480.7     24219.3      45114.6         48700.0    3585.4\n48  2018-12-01      21093.1     22399.2      42566.5         43492.3     925.8\n49  2019-01-01      21400.7     23130.2      41553.6         44530.9    2977.3\n50  2019-02-01      19909.7     19952.9      36074.4         39862.6    3788.2\n51  2019-03-01      20723.8     23508.3      40340.1         44232.1    3892.0\n52  2019-04-01      21486.6     22652.2      41294.9         44138.8    2843.9\n53  2019-05-01      23259.1     23372.5      42637.6         46631.6    3994.0\n54  2019-06-01      19933.0     21491.1      38979.9         41424.1    2444.2\n55  2019-07-01      21144.2     24246.7      42030.0         45390.9    3360.9\n56  2019-08-01      20850.4     24307.6      40998.2         45158.0    4159.8\n57  2019-09-01      19546.0     23948.3      39450.6         43494.3    4043.7\n58  2019-10-01      21927.3     24901.1      42282.5         46828.4    4545.9\n59  2019-11-01      21027.8     24731.0      42489.9         45758.8    3268.9\n60  2019-12-01      20385.0     24678.7      41580.6         45063.7    3483.1\n61  2020-01-01      21635.0     22866.6      41180.2         44501.6    3321.4\n62  2020-02-01      21069.5     22442.8      39472.6         43512.3    4039.7\n63  2020-03-01      22373.5     23426.5      40433.0         45800.0    5367.0\n64  2020-04-01      19246.4     20700.2      35878.8         39946.6    4067.8\n65  2020-05-01      16915.5     19566.8      31458.2         36482.3    5024.1\n66  2020-06-01      18021.1     22619.7      35120.9         40640.8    5519.9\n67  2020-07-01      19502.9     23389.8      37843.6         42892.7    5049.1\n68  2020-08-01      20063.2     24270.5      36472.3         44333.7    7861.4\n69  2020-09-01      18815.7     25091.8      38801.4         43907.5    5106.1\n70  2020-10-01      18651.6     25436.8      38173.8         44088.4    5914.6\n71  2020-11-01      18017.3     25274.7      38477.9         43292.0    4814.1\n72  2020-12-01      20137.9     26108.9      40154.5         46246.8    6092.3\n73  2021-01-01      20202.2     24786.6      39028.6         44988.8    5960.2\n74  2021-02-01      19517.4     23084.8      37643.7         42602.2    4958.5\n75  2021-03-01      25218.4     30225.7      47668.4         55444.1    7775.7\n76  2021-04-01      22801.9     27790.0      45169.5         50591.9    5422.4\n77  2021-05-01      21616.3     25738.9      41559.7         47355.2    5795.5\n78  2021-06-01      23737.8     25881.2      45039.8         49619.0    4579.2\n79  2021-07-01      23284.6     26549.4      46107.8         49834.0    3726.2\n80  2021-08-01      23119.3     28919.2      44714.5         52038.5    7324.0\n81  2021-09-01      22928.6     29105.5      45980.4         52034.1    6053.7\n82  2021-10-01      23992.9     29646.4      47945.2         53639.3    5694.1\n83  2021-11-01      26480.9     30239.2      50674.9         56720.1    6045.2\n84  2021-12-01      26075.1     33138.7      54349.4         59213.8    4864.4\n85  2022-01-01      24736.8     30108.9      50026.8         54845.7    4818.9\n86  2022-02-01      24202.3     27789.2      44958.4         51991.5    7033.1\n87  2022-03-01      29495.6     33637.0      58080.0         63132.6    5052.6\n88  2022-04-01      28376.1     31861.3      56116.0         60237.4    4121.4\n89  2022-05-01      29142.3     30705.1      57604.3         59847.4    2243.1\n90  2022-06-01      30072.1     34104.9      59649.2         64177.0    4527.8\n91  2022-07-01      30998.1     33126.9      61029.4         64125.0    3095.6\n92  2022-08-01      30220.5     33143.3      58466.0         63363.8    4897.8\n93  2022-09-01      27479.1     35028.0      55799.3         62507.1    6707.8\n94  2022-10-01      25546.0     31030.4      53182.9         56576.4    3393.5\n95  2022-11-01      24976.4     29186.4      50653.9         54162.8    3508.9\n96  2022-12-01      24423.6     30576.5      49869.8         55000.1    5130.3\n97  2023-01-01      22361.4     27169.8      44382.9         49531.2    5148.3\n98  2023-02-01      22273.8     28002.9      42748.4         50276.7    7528.3\n99  2023-03-01      27554.9     31516.9      51593.3         59071.8    7478.5\n100 2023-04-01      24015.0     25294.1      44966.7         49309.1    4342.4\n101 2023-05-01      23026.6     27704.0      45562.0         50730.6    5168.6\n102 2023-06-01      23470.0     29604.3      46726.3         53074.3    6348.0\n103 2023-07-01      22445.5     29856.1      46574.6         52301.6    5727.0\n104 2023-08-01      23134.7     30428.1      49260.0         53562.8    4302.8\n105 2023-09-01      23093.3     31343.3      48959.2         54436.6    5477.4\n106 2023-10-01      26297.7     31772.3      51889.5         58070.0    6180.5\n107 2023-11-01      24833.9     30728.5      49402.4         55562.4    6160.0\n108 2023-12-01      22546.0     29930.3      45253.9         52476.3    7222.4\n109 2024-01-01      25136.8     32555.4      49246.6         57692.2    8445.6\n110 2024-02-01      23159.9     27952.7      45008.5         51112.6    6104.1\n111 2024-03-01      24093.9     32945.3      51339.9         57039.2    5699.3\n112 2024-04-01      24062.9     31760.6      52901.0         55823.5    2922.5\n113 2024-05-01      25555.3     31257.7      52681.4         56813.0    4131.6\n114 2024-06-01      22945.7     29062.7      48845.9         52008.4    3162.5\n115 2024-07-01      26421.3     32806.7      52965.2         59228.0    6262.8\n116 2024-08-01      23984.0     31776.5      49949.0         55760.5    5811.5\n117 2024-09-01      21966.7     32477.4      49068.4         54444.1    5375.7\n118 2024-10-01      22147.8     33962.6      51415.6         56110.4    4694.8\n119 2024-11-01      23438.7     34891.5      51802.1         58330.2    6528.1\n120 2024-12-01      23684.7     36458.2      56135.9         60142.9    4007.0\n    Trade_Bal_MoM_Pct\n1                  NA\n2              -32.77\n3               49.91\n4              -31.41\n5               13.41\n6              -19.45\n7               15.77\n8              -40.60\n9               63.25\n10              41.36\n11             -26.14\n12               3.88\n13               4.46\n14             -75.92\n15             257.50\n16              26.77\n17              -8.47\n18             -12.53\n19              19.52\n20             -18.49\n21              35.85\n22             -17.50\n23             -22.92\n24              10.04\n25             -24.50\n26              72.31\n27              -3.53\n28              -3.22\n29             -18.56\n30              23.19\n31              -2.59\n32               0.13\n33              -5.47\n34             -19.35\n35               0.38\n36               1.81\n37              25.53\n38             -23.22\n39              35.36\n40               4.32\n41             -10.44\n42             -15.22\n43             -28.13\n44              99.34\n45             -33.64\n46               2.69\n47             -20.84\n48             -74.18\n49             221.59\n50              27.24\n51               2.74\n52             -26.93\n53              40.44\n54             -38.80\n55              37.51\n56              23.77\n57              -2.79\n58              12.42\n59             -28.09\n60               6.55\n61              -4.64\n62              21.63\n63              32.86\n64             -24.21\n65              23.51\n66               9.87\n67              -8.53\n68              55.70\n69             -35.05\n70              15.83\n71             -18.61\n72              26.55\n73              -2.17\n74             -16.81\n75              56.82\n76             -30.26\n77               6.88\n78             -20.99\n79             -18.63\n80              96.55\n81             -17.34\n82              -5.94\n83               6.17\n84             -19.53\n85              -0.94\n86              45.95\n87             -28.16\n88             -18.43\n89             -45.57\n90             101.85\n91             -31.63\n92              58.22\n93              36.96\n94             -49.41\n95               3.40\n96              46.21\n97               0.35\n98              46.23\n99              -0.66\n100            -41.93\n101             19.03\n102             22.82\n103             -9.78\n104            -24.87\n105             27.30\n106             12.84\n107             -0.33\n108             17.25\n109             16.94\n110            -27.72\n111             -6.63\n112            -48.72\n113             41.37\n114            -23.46\n115             98.03\n116             -7.21\n117             -7.50\n118            -12.67\n119             39.05\n120            -38.62\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntrade_data_longterm$Date_YM <- as.character(trade_data_longterm$Date_YM)\n\ntrade_data_longterm$Date <- as.Date(trade_data_longterm$Date_YM)\n\n\nif(sum(is.na(trade_data_longterm$Date)) > 0) {\n\n  trade_data_longterm$Date <- as.Date(trade_data_longterm$Date_YM, format=\"%Y-%m-%d\")\n\n}\n\n\nnames(trade_data_longterm)[names(trade_data_longterm) == \"DomExp_Value\"] <- \"Domestic_Exports\"\nnames(trade_data_longterm)[names(trade_data_longterm) == \"ReExp_Value\"] <- \"Re_Exports\"\nnames(trade_data_longterm)[names(trade_data_longterm) == \"Import_Value\"] <- \"Imports\"\nnames(trade_data_longterm)[names(trade_data_longterm) == \"Total_Exp_Value\"] <- \"Total_Exports\"\nnames(trade_data_longterm)[names(trade_data_longterm) == \"Trade_Bal\"] <- \"Trade_Balance\"\n\n\ntrade_data_longterm <- trade_data_longterm %>%\n  arrange(Date)\n\n\npre_covid_data <- trade_data_longterm[trade_data_longterm$Date < as.Date(\"2020-01-01\"), ]\ncovid_data <- trade_data_longterm[trade_data_longterm$Date >= as.Date(\"2020-01-01\") & \n                                trade_data_longterm$Date <= as.Date(\"2021-12-01\"), ]\npost_covid_data <- trade_data_longterm[trade_data_longterm$Date > as.Date(\"2021-12-01\"), ]\n\n\nstart_date <- min(trade_data_longterm$Date, na.rm=TRUE)\nstart_year <- as.numeric(format(start_date, \"%Y\"))\nstart_month <- as.numeric(format(start_date, \"%m\"))\n\nts_total_exports <- ts(trade_data_longterm$Total_Exports, \n                     start=c(start_year, start_month), \n                     frequency=12)\n\n\n\nif(start_year <= 2019 && nrow(covid_data) > 0 && nrow(post_covid_data) > 0) {\n\n  pre_covid_end_year <- 2019\n  pre_covid_end_month <- 12\n  \n  covid_start_year <- 2020\n  covid_start_month <- 1\n  covid_end_year <- min(2021, as.numeric(format(max(covid_data$Date, na.rm=TRUE), \"%Y\")))\n  covid_end_month <- as.numeric(format(max(covid_data$Date[format(covid_data$Date, \"%Y\") == as.character(covid_end_year)], na.rm=TRUE), \"%m\"))\n  \n  post_covid_start_year <- as.numeric(format(min(post_covid_data$Date, na.rm=TRUE), \"%Y\"))\n  post_covid_start_month <- as.numeric(format(min(post_covid_data$Date, na.rm=TRUE), \"%m\"))\n  \n\n  pre_covid <- window(ts_total_exports, \n                     end=c(pre_covid_end_year, pre_covid_end_month))\n  print(paste(start(pre_covid)[1], start(pre_covid)[2], \"-\", end(pre_covid)[1], end(pre_covid)[2]))\n  \n  covid_period <- window(ts_total_exports, \n                        start=c(covid_start_year, covid_start_month), \n                        end=c(covid_end_year, covid_end_month))\n  print(paste(start(covid_period)[1], start(covid_period)[2], \"-\", end(covid_period)[1], end(covid_period)[2]))\n  \n  post_covid <- window(ts_total_exports, \n                      start=c(post_covid_start_year, post_covid_start_month))\n  print(paste(start(post_covid)[1], start(post_covid)[2], \"-\", end(post_covid)[1], end(post_covid)[2]))\n  \n\n  pre_covid_mean <- mean(pre_covid, na.rm=TRUE)\n  covid_period_mean <- mean(covid_period, na.rm=TRUE)\n  post_covid_mean <- mean(post_covid, na.rm=TRUE)\n  \n  pre_covid_sd <- sd(pre_covid, na.rm=TRUE)\n  covid_period_sd <- sd(covid_period, na.rm=TRUE)\n  post_covid_sd <- sd(post_covid, na.rm=TRUE)\n  \n  \n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2015 1 - 2019 12\"\n[1] \"2020 1 - 2021 12\"\n[1] \"2022 1 - 2024 12\"\n```\n\n\n:::\n:::\n\n\n\n### Basic Chart\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrade_plot <- ggplot(trade_data_longterm, aes(x=Date)) +\n  geom_line(aes(y=Total_Exports, color=\"Total Exports\")) +\n  geom_line(aes(y=Domestic_Exports, color=\"Domestic Exports\")) +\n  geom_line(aes(y=Re_Exports, color=\"Re-Exports\")) +\n  geom_line(aes(y=Imports, color=\"Imports\")) +\n  labs(title=\"Trade Trends (2015-2024)\",\n       y=\"Value (Million Dollars)\",\n       color=\"Data Series\") +\n  scale_color_manual(values=c(\"Total Exports\"=\"blue\", \n                            \"Domestic Exports\"=\"green\", \n                            \"Re-Exports\"=\"purple\", \n                            \"Imports\"=\"red\")) +\n  theme_minimal()\n\n# Add COVID-19 marker line (if data range is sufficient)\nif(any(trade_data_longterm$Date >= as.Date(\"2020-03-01\"))) {\n  trade_plot <- trade_plot +\n    geom_vline(xintercept=as.Date(\"2020-03-01\"), \n              linetype=\"dashed\", color=\"darkred\") +\n    annotate(\"text\", x=as.Date(\"2020-03-15\"), \n             y=max(trade_data_longterm$Imports, na.rm=TRUE) * 0.95, \n             label=\"COVID-19\", color=\"darkred\", angle=90, hjust=0.5,vjust=1)\n}\n\n# Output the chart\nprint(trade_plot)\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n![](images/clipboard-539425624.png)\n\nKey points from the trade trends (2015-2024) visualization:\n\n1.  Four metrics tracked: Domestic Exports, Imports, Re-Exports, and Total Exports, all showing general upward trends over the decade.\n\n2.  COVID-19 (early 2020) caused significant disruption with sharp declines across all categories, particularly imports.\n\n3.  Strong post-COVID recovery (2021-2022) with steeper growth curves than pre-pandemic.\n\n4.  Recent divergent patterns (2022-2024): Total Exports and Re-Exports growing strongly, while Domestic Exports show concerning decline.\n\n5.  Widening gap between Total Exports and Domestic Exports indicates structural shift toward intermediary trade rather than domestic production.\n\n6.  Trade balance remained positive throughout, with Total Exports consistently exceeding Imports despite market disruptions.\n\n7.  Rising Re-Exports coupled with declining Domestic Exports suggests potential challenges in local production capacity or international competitiveness.\n\n### ACF & PACF Analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Create a Custom ACF/PACF Plot Function (Using Integer Lag Values)\ncustom_acf_plot <- function(series, series_name, lag_months = 24) {\n  # Ensure there are no NA values\n  series <- na.omit(series)\n  \n  # Set the layout for ACF and PACF plots\n  par(mfrow = c(2, 1), mar = c(4, 4, 2, 2), mgp = c(2, 0.7, 0))\n  \n  # Compute ACF and PACF values\n  acf_values <- acf(series, lag.max = lag_months, plot = FALSE)\n  pacf_values <- pacf(series, lag.max = lag_months, plot = FALSE)\n  \n  # Create a custom ACF plot (integer axis)\n  plot(0:lag_months, acf_values$acf, type = \"h\", \n       xlab = \"Lag (Months)\", ylab = \"ACF\", \n       main = paste(\"ACF:\", series_name),\n       ylim = c(min(acf_values$acf) - 0.1, 1), \n       xaxt = \"n\")  # Disable default x-axis\n  \n  # Add a custom x-axis (integer labels)\n  axis(1, at = 0:lag_months, labels = 0:lag_months)\n  \n  # Add horizontal lines for significance levels\n  abline(h = 0, col = \"black\")\n  abline(h = c(-1.96/sqrt(length(series)), 1.96/sqrt(length(series))), \n         col = \"blue\", lty = 2)\n  \n  # Create a custom PACF plot (integer axis)\n  plot(1:lag_months, pacf_values$acf, type = \"h\", \n       xlab = \"Lag (Months)\", ylab = \"PACF\", \n       main = paste(\"PACF:\", series_name),\n       ylim = c(min(pacf_values$acf) - 0.1, max(pacf_values$acf) + 0.1),\n       xaxt = \"n\")  # Disable default x-axis\n  \n  # Add a custom x-axis (integer labels)\n  axis(1, at = 1:lag_months, labels = 1:lag_months)\n  \n  # Add horizontal lines\n  abline(h = 0, col = \"black\")\n  abline(h = c(-1.96/sqrt(length(series)), 1.96/sqrt(length(series))), \n         col = \"blue\", lty = 2)\n}\n\n# 2. Create Time Series Objects for Each Series (If Not Created Previously)\n# Ensure there are no NA values and that data is valid\nts_total_exports <- ts(na.omit(trade_data_longterm$Total_Exports), \n                      start = c(start_year, start_month), \n                      frequency = 12)\nts_domestic_exports <- ts(na.omit(trade_data_longterm$Domestic_Exports), \n                         start = c(start_year, start_month), \n                         frequency = 12)\nts_re_exports <- ts(na.omit(trade_data_longterm$Re_Exports), \n                   start = c(start_year, start_month), \n                   frequency = 12)\nts_imports <- ts(na.omit(trade_data_longterm$Imports), \n                start = c(start_year, start_month), \n                frequency = 12)\nts_trade_balance <- ts(na.omit(trade_data_longterm$Trade_Balance), \n                      start = c(start_year, start_month), \n                      frequency = 12)\n\n# 3. Analyze Time Series Patterns Over the Entire Period\n\n# ACF/PACF Analysis for Total Exports\ncustom_acf_plot(ts_total_exports, \"Total Exports\")\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# ACF/PACF Analysis for Domestic Exports\ncustom_acf_plot(ts_domestic_exports, \"Domestic Exports\")\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# ACF/PACF Analysis for Re-Exports\ncustom_acf_plot(ts_re_exports, \"Re-Exports\")\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-21-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# ACF/PACF Analysis for Imports\ncustom_acf_plot(ts_imports, \"Imports\")\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-21-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# ACF/PACF Analysis for Trade Balance\ncustom_acf_plot(ts_trade_balance, \"Trade Balance\")\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-21-5.png){width=672}\n:::\n:::\n\n\n\n::: panel-tabset\n## 111\n\n![](images/50d3b06fd9104394297fa8c746b8c77.png)\n\nThe ACF plot shows a slowly decaying pattern, starting near 1.0 at lag 0 and gradually diminishing across the 24-month period. All values exceed the significance threshold (blue dotted line at 0.2) until around lag 21-22. This slow decay pattern is typical of non-stationary time series with strong persistence, suggesting either trend components or high-order autoregressive processes.\n\nThe PACF plot shows significant spikes primarily at lags 1, 2, and 3, with most subsequent values falling within the significance bands (±0.2). There's a smaller significant spike around lag 12, suggesting a possible annual seasonal component in the export data.\n\nThe combination of slowly decaying ACF and sharp cutoff after lag 3 in the PACF strongly indicates an AR(3) model would be appropriate for forecasting. The statistically significant partial autocorrelation at these first three lags suggests that export values are directly influenced by their values from the previous three months.\n\n## 222\n\n![](images/8a8115911a9854df51c7e3caacc0059.png)\n\nThe ACF plot shows a gradual decay pattern starting from 1.0 at lag 0 and diminishing over time. Values remain above the significance threshold (blue dotted line at approximately 0.2) until around lag 17-18. This slow decay pattern suggests strong persistence in the time series, indicating either trend components or high-order autoregressive processes in domestic export data.\n\nThe PACF plot shows significant positive spikes at lags 1, 2, and 3 (with values around 0.8, 0.2, and 0.2 respectively). Most subsequent lags fall within the significance bands (±0.2), with some negative values at lags 13 and 18. The sharp cutoff after lag 3 is a classic indicator of an AR(3) process.\n\n## 333\n\n![](images/eb3208b3a440a9e3fdf601b6c48db69.png)\n\nThe ACF plot shows an extremely slow decay starting from approximately 1.0 at lag 0 and declining very gradually through all 24 lags. Even at lag 24, the autocorrelation remains above 0.4, which is much higher than the previous export types. No significance threshold line is visible in this ACF plot, but all values would clearly exceed typical significance levels. This exceptionally slow decay suggests a highly persistent, likely non-stationary time series with strong long-term memory.\n\nThe PACF plot shows a different pattern compared to the previous export types. There's a significant spike at lag 1 (around 0.8), followed by smaller significant spikes at lags 2 and 3. Additionally, there's another notable spike at lag 12, suggesting a potential annual seasonal component. The blue dotted significance lines are at approximately ±0.2.\n\n## 444\n\n![](images/6401935fd1556aaec2b90c03ead8575.png)\n\nThe ACF plot shows a gradual decay pattern starting at 1.0 for lag 0 and decreasing steadily across all 24 lags. All values remain above the significance threshold (blue dotted line at approximately 0.2) until around lag 21-22. This slow decay pattern indicates strong persistence in the imports time series, suggesting non-stationarity and potentially long-term trend components.\n\nThe PACF plot displays significant positive spikes at lags 1, 2, and 3, with values of approximately 0.8, 0.2, and 0.1 respectively. Additional significant spikes appear at lags 12 and 24, strongly suggesting annual seasonality in import patterns. The significance bands are marked at ±0.2 by blue dotted lines.\n\n## 555\n\n![](images/0fd0a61eec35033b6bd18832ff18b8a.png)\n\nThe ACF plot displays a sharp drop after lag 0 (which is 1.0 by definition). Only the first few lags (approximately lags 1-6) show values above the significance threshold (blue dotted line at 0.2), with the values quickly diminishing to near zero. After lag 15, some negative autocorrelations appear, particularly around lags 19-22, suggesting possible cyclical behavior or negative feedback in the trade balance.\n\nThe PACF plot shows a more complex pattern with scattered significant spikes. There's a significant positive spike at lag 1 (around 0.3), and smaller significant spikes at lags 2, 5, 6, 10, and 23. Some negative spikes appear at lags 8, 12, 14, 16, and 19. The significance bands are at approximately ±0.2.\n:::\n\n### Seasonal Patterns and Decompose Time Series\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze Seasonal Patterns and Decompose Time Series\n# Ensure the time series length is sufficient for decomposition\nif(length(ts_total_exports) >= 24) {\n  # Decompose time series into trend, seasonal, and remainder components\n  decomp_total_exports <- decompose(ts_total_exports)\n  \n  # Save current graphic parameters\n  old_par <- par(no.readonly = TRUE)\n  \n  # Plot decomposition results\n  par(mfrow = c(4, 1), mar = c(2, 4, 2, 2))\n  plot(decomp_total_exports$x, main = \"Original Time Series of Total Exports\", ylab = \"Value\")\n  plot(decomp_total_exports$trend, main = \"Trend\", ylab = \"Trend\")\n  plot(decomp_total_exports$seasonal, main = \"Seasonal\", ylab = \"Seasonal\")\n  plot(decomp_total_exports$random, main = \"Random\", ylab = \"Random\")\n  \n} \n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze Seasonal Patterns and Decompose Time Series\n# Ensure the time series length is sufficient for decomposition\nif(length(ts_imports) >= 24) {\n  # Decompose time series into trend, seasonal, and remainder components\n  decomp_imports <- decompose(ts_imports)\n  \n  # Save current graphic parameters\n  old_par <- par(no.readonly = TRUE)\n  \n  # Plot decomposition results\n  par(mfrow = c(4, 1), mar = c(2, 4, 2, 2))\n  plot(decomp_imports$x, main = \"Original Time Series of Imports\", ylab = \"Value\")\n  plot(decomp_imports$trend, main = \"Trend\", ylab = \"Trend\")\n  plot(decomp_imports$seasonal, main = \"Seasonal\", ylab = \"Seasonal\")\n  plot(decomp_imports$random, main = \"Random\", ylab = \"Random\")\n  \n} \n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n::: panel-tabset\n## 111\n\n![](images/clipboard-4269530419.png)\n\nThe decomposition of Total Exports reveals:\n\n-   **Original Time Series:** Exports range from 35,000 to 65,000 units, with an overall upward trend and significant fluctuations, especially a step increase around 2021-2022.\n\n-   **Trend Component:** Shows gradual growth from 2016 to 2018, stability from 2018 to 2020, substantial growth from 2020 to 2022, a slight decline in late 2022/early 2023, and renewed growth into 2024.\n\n-   **Seasonal Component:** Displays a clear, repeating annual pattern with sharp drops to around -4,000 units and recoveries to +2,000 units, indicating strong seasonality.\n\n-   **Random Component:** Residual fluctuations range between -5,000 and +3,000 units, with higher volatility during 2020, reflecting pandemic disruptions.\n\nThis decomposition supports the earlier ACF/PACF analysis, confirming the need for differencing and seasonal adjustments in time series modeling.\n\n## 222\n\n![](images/clipboard-3676925903.png)\n\nThe time series decomposition of Imports (2015-2024) shows striking similarities to Total Exports:\n\n1.  **Original Time Series**: Imports range from 30,000 to 60,000 units with an upward trend and a notable step increase around 2021-2022.\n\n    **Trend Component**: Displays a dip in 2016, gradual growth until 2018, pandemic-related decline in 2020, significant growth from 2020-2022, a dip in late 2022/early 2023, and recovery into 2024.\n\n    **Seasonal Component**: Exhibits a recurring pattern with drops to -4,000 units and recoveries to +1,000 units, showing stable seasonality.\n\n    **Random Component**: Fluctuates between -5,000 and +6,000 units, with a significant negative spike in 2020 and volatility spikes in 2022.\n\nThe similarity suggests both imports and exports are influenced by the same macroeconomic factors, sharing synchronized trade cycles and pandemic-related disruptions. This reinforces the need for multivariate time series modeling for forecasting.\n:::\n\n### Comparison of Seasonal Patterns Before, During, and After COVID-19\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyzing COVID-19 Impact on Seasonal Patterns\ncat(\"\\nAnalysis of COVID-19 Impact on Seasonal Patterns:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAnalysis of COVID-19 Impact on Seasonal Patterns:\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ensure sufficient data points for analysis\nif(start_year <= 2019 && nrow(covid_data) > 0) {\n  # Split data into pre-COVID, during-COVID, and post-COVID periods\n  pre_covid_ts <- window(ts_total_exports, end = c(2019, 12))\n  during_covid_ts <- window(ts_total_exports, start = c(2020, 1), end = c(2021, 12))\n  post_covid_ts <- window(ts_total_exports, start = c(2022, 1))\n  \n  # Ensure all time series have sufficient length\n  if(length(pre_covid_ts) >= 12 && length(during_covid_ts) >= 12 && length(post_covid_ts) >= 12) {\n    # Decompose the three time series\n    pre_covid_decomp <- decompose(pre_covid_ts)\n    during_covid_decomp <- decompose(during_covid_ts)\n    post_covid_decomp <- decompose(post_covid_ts)\n    \n    # Extract seasonal components\n    pre_covid_seasonal <- pre_covid_decomp$seasonal\n    during_covid_seasonal <- during_covid_decomp$seasonal\n    post_covid_seasonal <- post_covid_decomp$seasonal\n    \n    # Extract first 12 months of each seasonal pattern for comparison\n    pre_covid_seasonal_pattern <- pre_covid_seasonal[1:12]\n    during_covid_seasonal_pattern <- during_covid_seasonal[1:12]\n    post_covid_seasonal_pattern <- post_covid_seasonal[1:12]\n    \n    # Create dataframe for easier plotting\n    seasonal_comparison <- data.frame(\n      Month = 1:12,\n      PreCOVID = as.numeric(pre_covid_seasonal_pattern),\n      DuringCOVID = as.numeric(during_covid_seasonal_pattern),\n      PostCOVID = as.numeric(post_covid_seasonal_pattern)\n    )\n    \n    # Convert to long format for ggplot\n    seasonal_comparison_long <- reshape2::melt(seasonal_comparison, \n                                             id.vars = \"Month\", \n                                             variable.name = \"Period\", \n                                             value.name = \"Seasonal\")\n    \n    # Plot seasonal comparison using ggplot2\n    seasonal_plot <- ggplot(seasonal_comparison_long, aes(x = Month, y = Seasonal, color = Period)) +\n      geom_line() +\n      labs(title = \"Comparison of Seasonal Patterns Before, During, and After COVID-19\",\n           y = \"Seasonal Component\",\n           color = \"Period\") +\n      scale_color_manual(values = c(\"PreCOVID\" = \"blue\", \"DuringCOVID\" = \"red\", \"PostCOVID\" = \"green\"),\n                         labels = c(\"PreCOVID\" = \"Pre-COVID (before 2020)\", \n                                   \"DuringCOVID\" = \"During COVID (2020-2021)\", \n                                   \"PostCOVID\" = \"Post-COVID (2022 onwards)\")) +\n      theme_minimal() +\n      scale_x_continuous(breaks = 1:12, labels = month.abb)\n    \n    print(seasonal_plot)\n    \n    # Calculate correlations between seasonal patterns\n    cor_pre_during <- cor(pre_covid_seasonal_pattern, during_covid_seasonal_pattern)\n    cor_pre_post <- cor(pre_covid_seasonal_pattern, post_covid_seasonal_pattern)\n    cor_during_post <- cor(during_covid_seasonal_pattern, post_covid_seasonal_pattern)\n    \n    cat(\"Correlation between pre-COVID and during-COVID seasonal patterns:\", cor_pre_during, \"\\n\")\n    cat(\"Correlation between pre-COVID and post-COVID seasonal patterns:\", cor_pre_post, \"\\n\")\n    cat(\"Correlation between during-COVID and post-COVID seasonal patterns:\", cor_during_post, \"\\n\")\n    \n    # Calculate changes in seasonal amplitude\n    amplitude_pre <- max(pre_covid_seasonal_pattern) - min(pre_covid_seasonal_pattern)\n    amplitude_during <- max(during_covid_seasonal_pattern) - min(during_covid_seasonal_pattern)\n    amplitude_post <- max(post_covid_seasonal_pattern) - min(post_covid_seasonal_pattern)\n    \n    cat(\"\\nSeasonal amplitude changes:\\n\")\n    cat(\"Pre-COVID seasonal amplitude:\", amplitude_pre, \"\\n\")\n    cat(\"During-COVID seasonal amplitude:\", amplitude_during, \"\\n\")\n    cat(\"Post-COVID seasonal amplitude:\", amplitude_post, \"\\n\")\n    cat(\"Percentage change during COVID compared to pre-COVID:\", \n        round((amplitude_during - amplitude_pre) / amplitude_pre * 100, 2), \"%\\n\")\n    cat(\"Percentage change post-COVID compared to pre-COVID:\", \n        round((amplitude_post - amplitude_pre) / amplitude_pre * 100, 2), \"%\\n\")\n    \n  } else {\n    cat(\"Warning: Insufficient time series length for one or more periods to perform seasonal comparison analysis\\n\")\n  }\n} else {\n  cat(\"Warning: Insufficient data range to compare pre and post-COVID periods\\n\")\n}\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation between pre-COVID and during-COVID seasonal patterns: 0.4114815 \nCorrelation between pre-COVID and post-COVID seasonal patterns: 0.6219752 \nCorrelation between during-COVID and post-COVID seasonal patterns: 0.7035423 \n\nSeasonal amplitude changes:\nPre-COVID seasonal amplitude: 7290.606 \nDuring-COVID seasonal amplitude: 12182.26 \nPost-COVID seasonal amplitude: 7687.231 \nPercentage change during COVID compared to pre-COVID: 67.1 %\nPercentage change post-COVID compared to pre-COVID: 5.44 %\n```\n\n\n:::\n:::\n\n\n\n![](images/clipboard-3307205938.png)\n\n-   **Dramatic March spike during COVID**: A significant spike in March 2020-2021 (+8000 units) compared to pre-COVID (\\~1500) and post-COVID (\\~4000), likely due to panic buying and trade adjustments during the pandemic.\n-   **February seasonal low**: All periods show February as a consistent seasonal low (\\~-5000 units), indicating a persistent seasonal pattern.\n-   **Shifted seasonal patterns**:\n    -   Pre-COVID: Secondary peak in June and stronger October-November activity.\n\n    -   During COVID: March spike, followed by deeper May-June troughs.\n\n    -   Post-COVID: Recovery with stronger July-September activity.\n-   **Recovery evolution**: Post-COVID shows a new seasonal pattern, with stronger first-quarter recovery (March) and enhanced summer activity (July-September), but weaker year-end performance.\n-   **Pattern volatility**: The COVID period shows extreme fluctuations, while post-COVID patterns are moderating but not returning to pre-pandemic stability.\n\n### Annual Growth Rates Analysis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze Growth Rates Over Different Periods\ncat(\"\\nGrowth Rate Analysis Over Different Periods:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nGrowth Rate Analysis Over Different Periods:\n```\n\n\n:::\n\n```{.r .cell-code}\n# Use dplyr to calculate annual averages and growth rates\n# Ensure the Date column is correct and add Year and Month columns\ntrade_data_longterm <- trade_data_longterm %>%\n  mutate(year = format(Date, \"%Y\"),\n         month = format(Date, \"%m\"))\n\n# Group by year and calculate annual averages\nannual_averages <- trade_data_longterm %>%\n  group_by(year) %>%\n  summarize(\n    Avg_Total_Exports = mean(Total_Exports, na.rm = TRUE),\n    Avg_Domestic_Exports = mean(Domestic_Exports, na.rm = TRUE),\n    Avg_Re_Exports = mean(Re_Exports, na.rm = TRUE),\n    Avg_Imports = mean(Imports, na.rm = TRUE),\n    Avg_Trade_Balance = mean(Trade_Balance, na.rm = TRUE)\n  )\n\n# Calculate year-over-year growth rates\nannual_growth <- annual_averages %>%\n  mutate(\n    Total_Exports_Growth = (Avg_Total_Exports / lag(Avg_Total_Exports) - 1) * 100,\n    Domestic_Exports_Growth = (Avg_Domestic_Exports / lag(Avg_Domestic_Exports) - 1) * 100,\n    Re_Exports_Growth = (Avg_Re_Exports / lag(Avg_Re_Exports) - 1) * 100,\n    Imports_Growth = (Avg_Imports / lag(Avg_Imports) - 1) * 100\n  )\n\n# Display annual growth rates\ncat(\"\\nAnnual Growth Rates (%):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAnnual Growth Rates (%):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(annual_growth[, c(\"year\", \"Total_Exports_Growth\", \"Domestic_Exports_Growth\", \n                      \"Re_Exports_Growth\", \"Imports_Growth\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   year  Total_Exports_Growth Domestic_Exports_Growth Re_Exports_Growth\n   <chr>                <dbl>                   <dbl>             <dbl>\n 1 2015                 NA                     NA               NA     \n 2 2016                 -5.06                  -5.80            -4.37  \n 3 2017                 10.3                   15.8              5.24  \n 4 2018                  7.90                   8.42             7.36  \n 5 2019                 -4.17                 -10.5              2.33  \n 6 2020                 -3.17                  -6.81             0.0977\n 7 2021                 19.1                   19.0             19.2   \n 8 2022                 15.6                   18.2             13.5   \n 9 2023                -10.1                  -13.5             -7.09  \n10 2024                  5.65                   0.542            9.78  \n# ℹ 1 more variable: Imports_Growth <dbl>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create annual growth rate visualization with faceted line graphs\n# Convert data to long format for ggplot\ngrowth_data_long <- annual_growth %>%\n  select(year, Total_Exports_Growth, Domestic_Exports_Growth, Re_Exports_Growth, Imports_Growth) %>%\n  reshape2::melt(id.vars = \"year\", variable.name = \"Variable\", value.name = \"Growth\") %>%\n  na.omit()  # Remove NA values\n\n# Create faceted line plot for growth rates\nfaceted_line_plot <- ggplot(growth_data_long, aes(x = year, y = Growth, color = Variable, group = Variable)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  facet_wrap(~ Variable, labeller = labeller(Variable = c(\n    \"Total_Exports_Growth\" = \"Total Exports\",\n    \"Domestic_Exports_Growth\" = \"Domestic Exports\",\n    \"Re_Exports_Growth\" = \"Re-Exports\",\n    \"Imports_Growth\" = \"Imports\"\n  ))) +\n  labs(title = \"Annual Growth Rates of Trade Variables\",\n       y = \"Growth Rate (%)\",\n       x = \"Year\") +\n  theme_minimal() +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1),\n        legend.position = \"none\",\n        strip.text = element_text(face = \"bold\"),\n        panel.grid.minor = element_blank()) +\n  scale_color_brewer(palette = \"Set1\")\n\nprint(faceted_line_plot)\n```\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n![](images/clipboard-3998755352.png)\n\n-   **Pandemic Impact (2020-2021)**: All categories saw dramatic growth spikes in 2021 (15-20%), following the minimal or negative growth in 2020 due to the pandemic.\n-   **Synchronized Cycles**: The variables follow similar cycles: moderate growth (2017-2018), slowdown (2019-2020), recovery (2021), decline (2022-2023), and recovery (2024).\n-   **Volatility Differences**: Domestic Exports and Imports are more volatile, with extreme swings, while Total Exports show more stability.\n-   **2023 Contraction**: All variables contracted in 2023, especially Imports and Domestic Exports, likely due to the global slowdown and supply chain issues.\n-   **Recovery Trends**: Positive growth returns in early 2024, with Imports and Re-Exports recovering faster than Domestic Exports.\n-   **Domestic vs. Re-Export Differences**: Domestic Exports show more extreme growth and contractions, indicating greater sensitivity to economic changes than Re-Exports.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Time Series Forecasting - Multiple Model Comparison\ncat(\"\\nTime Series Forecasting - Multiple Model Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTime Series Forecasting - Multiple Model Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\nif(require(\"forecast\")) {\n  forecast_periods <- 12\n  \n  # Create lists to store models and forecast results\n  models_exports <- list()\n  forecasts_exports <- list()\n  accuracy_exports <- list()\n  \n  models_imports <- list()\n  forecasts_imports <- list()\n  accuracy_imports <- list()\n  \n  models_trade_balance <- list()\n  forecasts_trade_balance <- list()\n  accuracy_trade_balance <- list()\n  \n  # 1. ARIMA Models\n  cat(\"\\n1. ARIMA Models:\\n\")\n  \n  # Exports ARIMA\n  models_exports$arima <- tryCatch({\n    auto.arima(ts_total_exports)\n  }, error = function(e) {\n    cat(\"Exports ARIMA model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  if(!is.null(models_exports$arima)) {\n    forecasts_exports$arima <- forecast(models_exports$arima, h = forecast_periods)\n    cat(\"Exports ARIMA model summary:\\n\")\n    print(summary(models_exports$arima))\n  }\n  \n  # Imports ARIMA\n  models_imports$arima <- tryCatch({\n    auto.arima(ts_imports)\n  }, error = function(e) {\n    cat(\"Imports ARIMA model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  if(!is.null(models_imports$arima)) {\n    forecasts_imports$arima <- forecast(models_imports$arima, h = forecast_periods)\n    cat(\"Imports ARIMA model summary:\\n\")\n    print(summary(models_imports$arima))\n  }\n  \n  # Trade Balance ARIMA\n  models_trade_balance$arima <- tryCatch({\n    auto.arima(ts_trade_balance)\n  }, error = function(e) {\n    cat(\"Trade Balance ARIMA model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  if(!is.null(models_trade_balance$arima)) {\n    forecasts_trade_balance$arima <- forecast(models_trade_balance$arima, h = forecast_periods)\n    cat(\"Trade Balance ARIMA model summary:\\n\")\n    print(summary(models_trade_balance$arima))\n  }\n  \n  # 2. Exponential Smoothing Models (ETS)\n  cat(\"\\n2. Exponential Smoothing Models (ETS):\\n\")\n  \n  # Exports ETS\n  models_exports$ets <- tryCatch({\n    ets(ts_total_exports)\n  }, error = function(e) {\n    cat(\"Exports ETS model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  if(!is.null(models_exports$ets)) {\n    forecasts_exports$ets <- forecast(models_exports$ets, h = forecast_periods)\n    cat(\"Exports ETS model summary:\\n\")\n    print(summary(models_exports$ets))\n  }\n  \n  # Imports ETS\n  models_imports$ets <- tryCatch({\n    ets(ts_imports)\n  }, error = function(e) {\n    cat(\"Imports ETS model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  if(!is.null(models_imports$ets)) {\n    forecasts_imports$ets <- forecast(models_imports$ets, h = forecast_periods)\n    cat(\"Imports ETS model summary:\\n\")\n    print(summary(models_imports$ets))\n  }\n  \n  # Trade Balance ETS\n  models_trade_balance$ets <- tryCatch({\n    ets(ts_trade_balance)\n  }, error = function(e) {\n    cat(\"Trade Balance ETS model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  if(!is.null(models_trade_balance$ets)) {\n    forecasts_trade_balance$ets <- forecast(models_trade_balance$ets, h = forecast_periods)\n    cat(\"Trade Balance ETS model summary:\\n\")\n    print(summary(models_trade_balance$ets))\n  }\n  \n  # 3. Seasonal Naive Models\n  cat(\"\\n3. Seasonal Naive Models:\\n\")\n  \n  # Determine seasonal frequency, default is 12 (monthly data)\n  freq <- frequency(ts_total_exports)\n  \n  # Exports SNaive\n  models_exports$snaive <- \"snaive\" # Just a marker, not an actual model object\n  forecasts_exports$snaive <- tryCatch({\n    snaive(ts_total_exports, h = forecast_periods)\n  }, error = function(e) {\n    cat(\"Exports Seasonal Naive model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  # Imports SNaive\n  models_imports$snaive <- \"snaive\"\n  forecasts_imports$snaive <- tryCatch({\n    snaive(ts_imports, h = forecast_periods)\n  }, error = function(e) {\n    cat(\"Imports Seasonal Naive model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  # Trade Balance SNaive\n  models_trade_balance$snaive <- \"snaive\"\n  forecasts_trade_balance$snaive <- tryCatch({\n    snaive(ts_trade_balance, h = forecast_periods)\n  }, error = function(e) {\n    cat(\"Trade Balance Seasonal Naive model error:\", e$message, \"\\n\")\n    return(NULL)\n  })\n  \n  # Model Comparison\n  cat(\"\\nModel Comparison - Accuracy Assessment:\\n\")\n  \n  # Calculate training set accuracy for each model\n  cat(\"\\nExports Model Comparison:\\n\")\n  if(length(forecasts_exports) > 0) {\n    # Extract accuracy metrics for each model\n    for(model_name in names(forecasts_exports)) {\n      if(!is.null(forecasts_exports[[model_name]])) {\n        accuracy_exports[[model_name]] <- accuracy(forecasts_exports[[model_name]])\n      }\n    }\n    \n    # Create comparison table\n    accuracy_table_exports <- do.call(rbind, lapply(names(accuracy_exports), function(model) {\n      data.frame(\n        Model = model,\n        RMSE = accuracy_exports[[model]][\"Training set\", \"RMSE\"],\n        MAE = accuracy_exports[[model]][\"Training set\", \"MAE\"],\n        MAPE = accuracy_exports[[model]][\"Training set\", \"MAPE\"],\n        AIC = if(model == \"arima\") AIC(models_exports$arima) else \n              if(model == \"ets\") AIC(models_exports$ets) else NA,\n        BIC = if(model == \"arima\") BIC(models_exports$arima) else \n              if(model == \"ets\") BIC(models_exports$ets) else NA\n      )\n    }))\n    \n    print(accuracy_table_exports)\n    \n    # Plot forecast comparison\n    if(length(forecasts_exports) > 1) {\n      # Prepare plot data\n      plot_data <- ts_total_exports\n      for(model_name in names(forecasts_exports)) {\n        if(!is.null(forecasts_exports[[model_name]])) {\n          # Add each model's forecast to the chart\n          plot_data <- cbind(plot_data, forecasts_exports[[model_name]]$mean)\n        }\n      }\n      \n      # Modify column names\n      colnames(plot_data) <- c(\"Actual\", names(forecasts_exports))\n      \n      # Draw comparison plot\n      plot(plot_data, plot.type = \"single\", col = 1:(1+length(forecasts_exports)),\n           main = \"Exports Forecast Model Comparison\",\n           xlab = \"Time\", ylab = \"Exports (Million Dollars)\")\n      legend(\"topleft\", colnames(plot_data), col = 1:(1+length(forecasts_exports)), lty = 1)\n    }\n  }\n  \n  # Imports Model Comparison\n  cat(\"\\nImports Model Comparison:\\n\")\n  if(length(forecasts_imports) > 0) {\n    # Extract accuracy metrics for each model\n    for(model_name in names(forecasts_imports)) {\n      if(!is.null(forecasts_imports[[model_name]])) {\n        accuracy_imports[[model_name]] <- accuracy(forecasts_imports[[model_name]])\n      }\n    }\n    \n    # Create comparison table\n    accuracy_table_imports <- do.call(rbind, lapply(names(accuracy_imports), function(model) {\n      data.frame(\n        Model = model,\n        RMSE = accuracy_imports[[model]][\"Training set\", \"RMSE\"],\n        MAE = accuracy_imports[[model]][\"Training set\", \"MAE\"],\n        MAPE = accuracy_imports[[model]][\"Training set\", \"MAPE\"],\n        AIC = if(model == \"arima\") AIC(models_imports$arima) else \n              if(model == \"ets\") AIC(models_imports$ets) else NA,\n        BIC = if(model == \"arima\") BIC(models_imports$arima) else \n              if(model == \"ets\") BIC(models_imports$ets) else NA\n      )\n    }))\n    \n    print(accuracy_table_imports)\n    \n    # Plot forecast comparison\n    if(length(forecasts_imports) > 1) {\n      # Prepare plot data\n      plot_data <- ts_imports\n      for(model_name in names(forecasts_imports)) {\n        if(!is.null(forecasts_imports[[model_name]])) {\n          # Add each model's forecast to the chart\n          plot_data <- cbind(plot_data, forecasts_imports[[model_name]]$mean)\n        }\n      }\n      \n      # Modify column names\n      colnames(plot_data) <- c(\"Actual\", names(forecasts_imports))\n      \n      # Draw comparison plot\n      plot(plot_data, plot.type = \"single\", col = 1:(1+length(forecasts_imports)),\n           main = \"Imports Forecast Model Comparison\",\n           xlab = \"Time\", ylab = \"Imports (Million Dollars)\")\n      legend(\"topleft\", colnames(plot_data), col = 1:(1+length(forecasts_imports)), lty = 1)\n    }\n  }\n  \n  # Trade Balance Model Comparison\n  cat(\"\\nTrade Balance Model Comparison:\\n\")\n  if(length(forecasts_trade_balance) > 0) {\n    # Extract accuracy metrics for each model\n    for(model_name in names(forecasts_trade_balance)) {\n      if(!is.null(forecasts_trade_balance[[model_name]])) {\n        accuracy_trade_balance[[model_name]] <- accuracy(forecasts_trade_balance[[model_name]])\n      }\n    }\n    \n    # Create comparison table\n    accuracy_table_trade_balance <- do.call(rbind, lapply(names(accuracy_trade_balance), function(model) {\n      data.frame(\n        Model = model,\n        RMSE = accuracy_trade_balance[[model]][\"Training set\", \"RMSE\"],\n        MAE = accuracy_trade_balance[[model]][\"Training set\", \"MAE\"],\n        MAPE = accuracy_trade_balance[[model]][\"Training set\", \"MAPE\"],\n        AIC = if(model == \"arima\") AIC(models_trade_balance$arima) else \n              if(model == \"ets\") AIC(models_trade_balance$ets) else NA,\n        BIC = if(model == \"arima\") BIC(models_trade_balance$arima) else \n              if(model == \"ets\") BIC(models_trade_balance$ets) else NA\n      )\n    }))\n    \n    print(accuracy_table_trade_balance)\n    \n    # Plot forecast comparison\n    if(length(forecasts_trade_balance) > 1) {\n      # Prepare plot data\n      plot_data <- ts_trade_balance\n      for(model_name in names(forecasts_trade_balance)) {\n        if(!is.null(forecasts_trade_balance[[model_name]])) {\n          # Add each model's forecast to the chart\n          plot_data <- cbind(plot_data, forecasts_trade_balance[[model_name]]$mean)\n        }\n      }\n      \n      # Modify column names\n      colnames(plot_data) <- c(\"Actual\", names(forecasts_trade_balance))\n      \n      # Draw comparison plot\n      plot(plot_data, plot.type = \"single\", col = 1:(1+length(forecasts_trade_balance)),\n           main = \"Trade Balance Forecast Model Comparison\",\n           xlab = \"Time\", ylab = \"Trade Balance (Million Dollars)\")\n      legend(\"topleft\", colnames(plot_data), col = 1:(1+length(forecasts_trade_balance)), lty = 1)\n    }\n  }\n  \n  # Cross-validation comparison (if data is sufficient)\n  cat(\"\\nModel Cross-Validation Comparison (Exports):\\n\")\n  tryCatch({\n    # Cross-validation for ARIMA model\n    if(!is.null(models_exports$arima)) {\n      cv_arima <- tsCV(ts_total_exports, function(x, h) forecast(auto.arima(x), h = h), h = 1)\n      cat(\"ARIMA model cross-validation RMSE:\", sqrt(mean(cv_arima^2, na.rm = TRUE)), \"\\n\")\n    }\n    \n    # Cross-validation for ETS model\n    if(!is.null(models_exports$ets)) {\n      cv_ets <- tsCV(ts_total_exports, function(x, h) forecast(ets(x), h = h), h = 1)\n      cat(\"ETS model cross-validation RMSE:\", sqrt(mean(cv_ets^2, na.rm = TRUE)), \"\\n\")\n    }\n    \n    # Cross-validation for Seasonal Naive model\n    cv_snaive <- tsCV(ts_total_exports, snaive, h = 1)\n    cat(\"Seasonal Naive model cross-validation RMSE:\", sqrt(mean(cv_snaive^2, na.rm = TRUE)), \"\\n\")\n  }, error = function(e) {\n    cat(\"Error during cross-validation process:\", e$message, \"\\n\")\n  })\n  \n} else {\n  cat(\"Warning: The forecast package is not installed, cannot perform time series forecasting and model comparison\\n\")}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n1. ARIMA Models:\nExports ARIMA model summary:\nSeries: ts_total_exports \nARIMA(0,1,1)(1,0,0)[12] \n\nCoefficients:\n          ma1    sar1\n      -0.4412  0.3864\ns.e.   0.0867  0.0969\n\nsigma^2 = 9917788:  log likelihood = -1127.46\nAIC=2260.92   AICc=2261.13   BIC=2269.26\n\nTraining set error measures:\n                   ME     RMSE      MAE        MPE     MAPE      MASE\nTraining set 186.6958 3109.637 2380.565 0.07601217 5.027877 0.4911395\n                    ACF1\nTraining set -0.01185582\nImports ARIMA model summary:\nSeries: ts_imports \nARIMA(3,1,0)(1,0,0)[12] \n\nCoefficients:\n          ar1      ar2     ar3    sar1\n      -0.2752  -0.1022  0.1489  0.4341\ns.e.   0.0997   0.1003  0.0971  0.0918\n\nsigma^2 = 8465099:  log likelihood = -1117.28\nAIC=2244.55   AICc=2245.08   BIC=2258.45\n\nTraining set error measures:\n                   ME     RMSE      MAE        MPE     MAPE      MASE\nTraining set 161.8475 2848.225 2184.842 0.09394294 5.154655 0.4220088\n                   ACF1\nTraining set 0.00219697\nTrade Balance ARIMA model summary:\nSeries: ts_trade_balance \nARIMA(2,0,2)(1,0,1)[12] with non-zero mean \n\nCoefficients:\n         ar1      ar2     ma1     ma2     sar1    sma1       mean\n      0.1632  -0.6547  0.0015  0.9332  -0.5068  0.7051  5098.5489\ns.e.  0.1376   0.2056  0.0507  0.2092   0.2574  0.2189   161.2325\n\nsigma^2 = 1564246:  log likelihood = -1023.74\nAIC=2063.49   AICc=2064.78   BIC=2085.79\n\nTraining set error measures:\n                    ME     RMSE      MAE       MPE     MAPE      MASE      ACF1\nTraining set -6.348112 1213.671 970.3565 -8.751244 23.57575 0.6604476 0.1123748\n\n2. Exponential Smoothing Models (ETS):\nExports ETS model summary:\nETS(M,N,A) \n\nCall:\nets(y = ts_total_exports)\n\n  Smoothing parameters:\n    alpha = 0.5665 \n    gamma = 1e-04 \n\n  Initial states:\n    l = 43541.2163 \n    s = 654.442 671.5779 1548.251 99.89 984.2043 688.6513\n           -624.6254 -380.9701 -825.3916 2793.719 -4305.296 -1304.453\n\n  sigma:  0.0563\n\n     AIC     AICc      BIC \n2480.458 2485.073 2522.270 \n\nTraining set error measures:\n                  ME   RMSE      MAE       MPE     MAPE      MASE       ACF1\nTraining set 214.772 2545.1 2039.289 0.2092063 4.325699 0.4207302 0.03319492\nImports ETS model summary:\nETS(M,N,A) \n\nCall:\nets(y = ts_imports)\n\n  Smoothing parameters:\n    alpha = 0.6634 \n    gamma = 1e-04 \n\n  Initial states:\n    l = 37889.4605 \n    s = 790.2295 1067.574 1280.973 -328.8356 578.7075 1111.39\n           -341.2553 -96.129 -492.8001 2015.657 -4336.178 -1249.334\n\n  sigma:  0.0598\n\n     AIC     AICc      BIC \n2467.197 2471.812 2509.009 \n\nTraining set error measures:\n                   ME     RMSE      MAE       MPE     MAPE     MASE       ACF1\nTraining set 198.6721 2383.642 1925.945 0.2209405 4.564492 0.372002 0.06552482\nTrade Balance ETS model summary:\nETS(M,N,N) \n\nCall:\nets(y = ts_trade_balance)\n\n  Smoothing parameters:\n    alpha = 0.2067 \n\n  Initial states:\n    l = 5939.6328 \n\n  sigma:  0.2566\n\n     AIC     AICc      BIC \n2299.900 2300.107 2308.263 \n\nTraining set error measures:\n                    ME     RMSE      MAE       MPE     MAPE      MASE\nTraining set -31.72322 1303.875 1005.294 -10.40738 25.66917 0.6842267\n                   ACF1\nTraining set 0.08746323\n\n3. Seasonal Naive Models:\n\nModel Comparison - Accuracy Assessment:\n\nExports Model Comparison:\n   Model     RMSE      MAE     MAPE      AIC      BIC\n1  arima 3109.637 2380.565 5.027877 2260.918 2269.255\n2    ets 2545.100 2039.289 4.325699 2480.458 2522.270\n3 snaive 6133.565 4847.023 9.676373       NA       NA\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nImports Model Comparison:\n   Model     RMSE      MAE      MAPE      AIC      BIC\n1  arima 2848.225 2184.842  5.154655 2244.551 2258.447\n2    ets 2383.642 1925.945  4.564492 2467.197 2509.009\n3 snaive 6522.537 5177.244 11.557466       NA       NA\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-27-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTrade Balance Model Comparison:\n   Model     RMSE       MAE     MAPE      AIC      BIC\n1  arima 1213.671  970.3565 23.57575 2063.486 2085.786\n2    ets 1303.875 1005.2937 25.66917 2299.900 2308.263\n3 snaive 1792.850 1469.2407 35.87981       NA       NA\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](作业21.0_files/figure-html/unnamed-chunk-27-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Cross-Validation Comparison (Exports):\nARIMA model cross-validation RMSE: 3280.391 \nETS model cross-validation RMSE: 3117.02 \nSeasonal Naive model cross-validation RMSE: 6133.565 \n```\n\n\n:::\n:::\n\n\n\n::: panel-tabset\n## 111\n\n![](images/clipboard-953888917.png)\n\nKey observations:\n\n-   Historical export data ranges from 35,000 to 60,000 million dollars, with stability from 2016-2019, a dip in early 2020 (likely COVID-related), strong growth from mid-2020 to 2022, and stabilization in 2023-2024 (50,000-58,000 million dollars).\n\n-   All models project continued export growth through 2026, reaching around 60,000 million dollars.\n\n-   The ARIMA model shows steady growth with moderate seasonal variations, ETS is similar but with less volatility, and SNAIVE has more pronounced seasonal patterns.\n\nThe alignment across models suggests confidence in ongoing export growth with less volatility than during the pandemic.\n\n## 222\n\n![](images/clipboard-3127309082.png)\n\nKey observations:\n\n-   Historical imports data ranges from 30,000 to 55,000 million dollars, with stability from 2016-2019, a dip in early 2020 (COVID-related), strong growth from mid-2020 to 2022, and moderation in 2023-2024 (45,000-50,000 million dollars).\n\n-   All models project continued growth through 2026, with differences:\n\n    -   ARIMA forecasts steady growth to 55,000 million dollars.\n\n    -   ETS predicts moderate growth to 52,000 million dollars.\n\n    -   SNAIVE shows more seasonality and conservative growth.\n\n## 333\n\n![](images/clipboard-3273941612.png)\n\nKey observations:\n\n1.  **Historical Data**: Trade Balance shows significant volatility, ranging from 1,000 to 8,500 million dollars, with a major dip in early 2018, substantial volatility from 2020-2023 due to pandemic disruptions, and a peak in late 2023/early 2024 around 8,500 million dollars.\n\n2.  **Forecasts**:\n\n    -   SNAIVE model projects the highest volatility, reflecting recent seasonal patterns.\n\n    -   ARIMA and ETS models show more moderate, stable forecasts.\n\n3.  **Projections**: All models predict Trade Balance will remain in the 3,000-6,500 million dollar range through 2026, with no return to the low values seen in 2018, suggesting continued trade surplus despite fluctuations.\n\n## 444\n\n# Key Findings - Time Series Forecasting Models Comparison\n\n## Best Models by Trade Component\n\n-   **Exports**: ETS(M,N,A) outperforms with lower RMSE (2,545 vs 3,110) and MAPE (4.33% vs 5.03%)\n\n-   **Imports**: ETS(M,N,A) superior with RMSE of 2,384 vs ARIMA's 2,848\n\n-   **Trade Balance**: ARIMA(2,0,2)(1,0,1)\\[12\\] slightly better with RMSE of 1,214 vs 1,304\n\n## Critical Points\n\n1.  **Model Accuracy**:\n\n    -   Exports/Imports: Strong forecasting accuracy (MAPE 4-5%)\n\n    -   Trade Balance: Higher uncertainty (MAPE \\>20%)\n\n2.  **Cross-Validation**:\n\n    -   Both ARIMA and ETS significantly outperform Seasonal Naive\n\n    -   ETS maintains edge over ARIMA (RMSE: 3,117 vs 3,280)\n\n3.  **Seasonal Patterns**:\n\n    -   Significant seasonality in exports and imports\n\n    -   Trade balance shows weaker seasonal effects\n\n4.  \n\n## Practical Applications\n\n-   Use ETS models for individual trade components (exports/imports)\n\n-   Consider ARIMA for trade balance forecasting\n\n-   Higher confidence in exports/imports forecasts than trade balance\n\n## 555\n:::\n",
    "supporting": [
      "作业21.0_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}