---
title: "In-class Exercise 7"

author: "xh.zhang"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

# Load packages

```{r}
pacman::p_load(tidyverse, tsibble, feasts, fable, seasonal)
```

# Load data

```{r}
ts_data <- read_csv(
  "data/visitor_arrivals_by_air.csv")
```

We noticed that Month-Year is in char format.

# Encode data into correct format

```{r}
ts_data$`Month-Year` <- dmy(
  ts_data$`Month-Year`)
```


# Convert into time series data frame

```{r}
ts_data_ts <- ts(ts_data)       
head(ts_data_ts)
```
# Convert into tsibble dataframe, then can be used by R.

```{r}
ts_tsibble <- ts_data %>%
  mutate(Month = yearmonth(`Month-Year`)) %>%
  as_tsibble(index = `Month`)
```

# Organise the data frame from wide to long format.

```{r}
ts_longer <- ts_data %>%
  pivot_longer(cols = c(2:34),
               names_to = "Country",
               values_to = "Arrivals")
```

# Visualising time-series

```{r}
ts_longer %>%
  filter(Country == "Vietnam") %>%
  ggplot(aes(x = `Month-Year`, 
             y = Arrivals))+
  geom_line(size = 0.5)+
  scale_y_continuous(labels = scales::dollar_format())
```

```{r}
#| fig-height: 15
ggplot(data = ts_longer, 
       aes(x = `Month-Year`, 
           y = Arrivals))+
  geom_line(size = 0.5) +
  facet_wrap(~ Country,
             ncol = 3,
             scales = "free_y")
```
# Cycle plot
```{r}
tsibble_longer <- ts_tsibble %>%
  pivot_longer(cols = c(2:34),
               names_to = "Country",
               values_to = "Arrivals")
```


```{r}
#| fig-height: 6
tsibble_longer %>%
  filter(Country == "Vietnam" |
         Country == "Italy") %>% 
  autoplot(Arrivals) + 
  facet_grid(Country ~ ., scales = "free_y")
```


```{r}
tsibble_longer %>%
  filter(Country == "Vietnam" |
         Country == "Italy") %>% 
  gg_subseries(Arrivals)
```
# ACF

```{r}
tsibble_longer %>%
  filter(`Country` == "Vietnam" |
         `Country` == "Italy" |
         `Country` == "United Kingdom" |
         `Country` == "China") %>%
  ACF(Arrivals) %>%
  autoplot()
```


